SanderMertens/flecs

CMakeLists.txt, include/bake_config.h, include/flecs.h, include/private/types.h, include/util/array.h, include/util/map.h, include/util/os_api.h, src/hash.c, src/system.c, src/table_system.c, src/time.c, src/type.c
=> WIP: Windows support

CMakeLists.txt, include/bake_config.h
* Implemented `static` lib target
* Implemented `shared` lib target
* Implemented targets installing
=> Improved `cmake` support

include/bake_config.h, include/util/os_api.h
A few tiny changes to add support for MinGW.
=> Fix compilation under Windows with MinGW

.gitignore, include/bake_config.h, include/private/flecs.h, src/os_api.c, src/os_time.c
This is a first step for an integrated os api that won't require bake_utils. 
Please let me know what you think
=> Os time implementation (from sokol_time.h)

README.md, include/flecs.h, include/flecs/util/os_api.h, include/flecs/util/stats.h, src/column_system.c, src/entity.c, src/flecs_private.h, src/misc.c, src/os_api.c, src/stage.c, src/stats.c, src/system.c, src/type.c, src/types.h, src/vector.c, src/world.c, test/api/project.json, test/api/src/SingleThreadStaging.c, test/api/src/Singleton.c, test/api/src/SystemOnDemand.c, test/api/src/System_w_FromEntity.c, test/api/src/Tasks.c, test/api/src/World.c, test/api/src/main.c
Redesign the statistics API into an embedded module which contains OnDemand systems that are only enabled when a system expresses interest in statistics
=> Statistics redesign

include/flecs/flecs.hpp
=> Small C++ Perf Opt: Mark invoker calls to capture by reference 

Manual.md
Noticed a couple of typos while reading through Manual.md, cheers!
=> Fix typos in Manual.md#specialization

src/hierarchy.c
=> is_number small optimization

CMakeLists.txt
Like the headline says.
cmake runs with the following output:
```cmd
E:\Workspace\flecs>mkdir build-flecs
E:\Workspace\flecs>cd build-flecs
E:\Workspace\flecs\build-flecs>cmake ..
-- Building for: Visual Studio 16 2019
-- Selecting Windows SDK version 10.0.18362.0 to target Windows 10.0.19041.
-- The C compiler identification is MSVC 19.27.29112.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.27.29110/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: E:/Workspace/flecs/build-flecs
E:\Workspace\flecs\build-flecs>cmake --build …
```
=> added_hpp_files_to_cmake_install

src/misc.c
thanks to @randy408 for digging up the solution
=> fixes ticks not being converted to nanoseconds

include/flecs/flecs.hpp
nothing special, just adding some functionality from c-api
=> cpp-api: add filter variants to query iteration

include/flecs/cpp/iter.hpp, test/cpp_api/src/QueryBuilder.cpp, test/cpp_api/src/SystemBuilder.cpp
It ain't much, but it's honest work
Fixes #407
=> #407 Added support for operator* on flecs::column

flecs.c, flecs.h, include/flecs.h, include/flecs/cpp/component.hpp, include/flecs/cpp/lifecycle_traits.hpp, include/flecs/private/vector.h, src/bootstrap.c, src/modules/system/system.c, src/private_types.h, src/table.c, src/world.c, test/api/project.json, test/api/src/ComponentLifecycle.c, test/api/src/Delete.c, test/api/src/DirectAccess.c, test/api/src/main.c, test/cpp_api/project.json, test/cpp_api/src/ComponentLifecycle.cpp, test/cpp_api/src/main.cpp
Ensure that moved from elements are destructed when components are removed/deleted.
=> #124 ensure that moved from component is destructed

flecs.c, flecs.h, src/private_types.h, src/query.c, src/table.c
Fixed issue with on set systems for pair types only triggering for changes to the last column of the match on a table
=> Fixed issue with on set systems for pair types

flecs.c, flecs.h, include/flecs.h, include/flecs/addons/cpp/builder.hpp, include/flecs/addons/cpp/invoker.hpp, src/addons/snapshot.c, src/addons/system/system.c, src/bootstrap.c, src/entity.c, src/filter.c, src/iter.c, src/private_api.h, src/private_types.h, src/query.c, src/table.c, src/table_graph.c, src/trigger.c
=> Compute storage type for tables

flecs.c, flecs.h, include/flecs.h, src/entity.c, test/api/project.json, test/api/src/New_w_Count.c, test/api/src/main.c
=> #502 add bulk_init function

flecs.c, flecs.h, include/flecs/addons/cpp/builder.hpp, include/flecs/addons/cpp/impl/builder.hpp, include/flecs/private/api_defines.h, src/addons/parser.c, src/api_support.c, src/entity.c, src/filter.c, src/query.c, src/type.c, test/api/project.json, test/api/src/Parser.c, test/api/src/Switch.c, test/api/src/main.c, test/cpp_api/project.json, test/cpp_api/src/QueryBuilder.cpp, test/cpp_api/src/Switch.cpp, test/cpp_api/src/main.cpp
Queries for a case now need to provide both the switch and case. See this discussion for more details: https://github.com/SanderMertens/flecs/discussions/466#discussioncomment-1605624
=> #124 change query case terms to a (switch, case) pair

docs/Queries.md, docs/Relations.md, flecs.c, flecs.h, include/flecs.h, include/flecs/addons/cpp/flecs.hpp, src/addons/coredoc.c, src/addons/rules.c, src/bootstrap.c, src/entity.c, src/table_graph.c, src/world.c, test/api/project.json, test/api/src/Hierarchies.c, test/api/src/Pairs.c, test/api/src/Plecs.c, test/api/src/Rules.c, test/api/src/System_w_FromParent.c, test/api/src/TransitiveRules.c, test/api/src/Trigger.c, test/api/src/World.c, test/api/src/main.c, test/cpp_api/project.json, test/cpp_api/src/Pairs.cpp, test/cpp_api/src/main.cpp
Add `Exclusive` constraint which ensures that an entity can never have more than one instance of a relation.
=> Add "Exclusive" constraint

include/flecs/addons/cpp/mixins/filter/builder_i.hpp
Added possible implementation of implicit InOut derived from term's T type like in Observer, lets see if it passes tests.
implements #558
=> #558 Retriving InOut type from term argument type

include/flecs/addons/cpp/impl/world.hpp, include/flecs/addons/cpp/invoker.hpp, include/flecs/addons/cpp/world.hpp
doing the same thing the entity does for `.get` and `.set` with lambdas
implements #560
=> #560 get and set for world

flecs.h, include/flecs/addons/cpp/impl/world.hpp
Removed the implementation of world ensure in cases where it is pre-defined
=> Remove implementation of world ensure

include/flecs/addons/cpp/entity_view.hpp, include/flecs/addons/cpp/mixins/entity/impl.hpp, test/cpp_api/project.json, test/cpp_api/src/Entity.cpp, test/cpp_api/src/main.cpp
=> added templated get_object method to entities

flecs.c, flecs.h, include/flecs/private/map.h, src/addons/rules.c, src/datastructures/map.c, src/entity.c, src/filter.c, src/observable.c, src/private_api.h, src/private_types.h, src/query.c, src/search.c, src/table.c, src/table_cache.c, src/table_cache.h, src/table_graph.c, src/world.c, test/api/src/OnDelete.c
This PR improves the design and performance of internal table administration data structures.
=> #124 improve table cache and graph storage

include/flecs.h
=> Fix FLECS_NDEBUG redifinition

include/flecs/addons/cpp/pair.hpp, include/flecs/addons/cpp/utils/signature.hpp, include/flecs/addons/cpp/utils/utils.hpp, test/cpp_api/project.json, test/cpp_api/src/FilterBuilder.cpp, test/cpp_api/src/main.cpp
Added a test case to cover terms with <const T*> for completeness. All 843 test cases completed successfully on my end.
=> Fix const optional terms asserting

flecs.c, flecs.h, include/flecs.h, include/flecs/private/api_defines.h, src/bootstrap.c, src/entity.c, src/observable.c, src/private_api.h, src/private_types.h, src/table.c, src/world.c, test/api/project.json, test/api/src/ComponentLifecycle.c, test/api/src/Pairs.c, test/api/src/Trigger.c, test/api/src/WorldInfo.c, test/api/src/main.c
This PR improves how component properties are configured and how type info is retrieved. It includes a fix for  issue https://github.com/SanderMertens/flecs/issues/637
=> Component lifecycle improvements

flecs.c, flecs.h, include/flecs/addons/cpp/component.hpp, include/flecs/addons/cpp/invoker.hpp, src/bootstrap.c, src/table.c, src/world.c, test/api/project.json, test/api/src/ComponentLifecycle.c, test/api/src/main.c, test/cpp_api/project.json, test/cpp_api/src/ComponentLifecycle.cpp, test/cpp_api/src/main.cpp
This PR adds add, remove and set component hooks to the C++ API.
=> Add component add, remove, set hooks to C++ API

docs/Manual.md, docs/Quickstart.md
Following changes that have been made to the flecs C API, and based on [the comment left in this discussion](https://github.com/SanderMertens/flecs/discussions/466#discussioncomment-1512601), the documentation for modules written in C has been updated to reflect these changes.
- Updated `docs/Manual.md`
- Updated `docs/Quickstart.md`
=> Updated C module documentation

flecs.c, flecs.h, include/flecs/addons/log.h, src/addons/pipeline/pipeline.c, src/addons/pipeline/pipeline.h, src/addons/pipeline/worker.c, src/addons/system/system.c, src/query.c, src/stage.c, src/world.c, test/addons/project.json, test/addons/src/MultiThread.c, test/addons/src/Parser.c, test/addons/src/main.c
=> #754 fix race condition with multithreaded apps and no_staging systems

src/addons/meta/cursor.c
Allow more types to be set with `ecs_meta_set_(u)int()`
Allow fields to be set to `NULL` with integers
=> meta: improve cursor api

flecs.h, include/flecs/addons/cpp/mixins/filter/impl.hpp
I think this was an oversight in the latest commit :)
=> Use stage argument in filter::get_iter method

flecs.c, flecs.h, include/flecs.h, include/flecs/addons/cpp/mixins/filter/builder.hpp, include/flecs/addons/cpp/mixins/filter/impl.hpp, include/flecs/addons/cpp/mixins/query/builder.hpp, include/flecs/addons/cpp/mixins/query/impl.hpp, include/flecs/addons/cpp/mixins/rule/builder.hpp, include/flecs/addons/cpp/mixins/rule/impl.hpp, src/addons/pipeline/pipeline.c, src/addons/rules.c, src/addons/system/system.c, src/filter.c, src/observer.c, src/poly.c, src/private_types.h, src/query.c, src/world.c, test/api/project.json, test/api/src/Poly.c, test/api/src/main.c, test/cpp_api/project.json, test/cpp_api/src/Filter.cpp, test/cpp_api/src/Query.cpp, test/cpp_api/src/RuleBuilder.cpp, test/cpp_api/src/main.cpp
This PR enables the creation of filters and rules that, like queries, can be associated with entities. For more information, see https://github.com/SanderMertens/flecs/discussions/466#discussioncomment-4149587
=> Allow for creation of named filters/rules

docs/Queries.md
As a follow-up to https://github.com/SanderMertens/flecs/pull/868, the surrounding documentation should also be updated.
=> Additional `Queries.md` Changes

include/flecs/addons/cpp/mixins/pipeline/impl.hpp, include/flecs/addons/cpp/mixins/pipeline/mixin.inl
don't know how to rebuild flecs.h
=> Let run_pipeline take entity_t

flecs.c, flecs.h, src/addons/pipeline/pipeline.c, src/addons/pipeline/pipeline.h, src/addons/pipeline/worker.c, src/addons/stats.c, src/datastructures/vec.c, test/addons/project.json, test/addons/src/MultiThread.c, test/addons/src/System_w_FromParent.c, test/addons/src/main.c, test/api/src/SingleThreadStaging.c
This PR contains a refactor of pipelines & workers, which simplifies code and fixes a number of issues.
=> #876 Pipeline refactor

docs/RestApi.md, flecs.c, flecs.h, include/flecs/addons/json.h, include/flecs/addons/meta.h, include/flecs/addons/parser.h, include/flecs/addons/rest.h, src/addons/expr/deserialize.c, src/addons/json/deserialize.c, src/addons/log.c, src/addons/meta/cursor.c, src/addons/parser.c, src/addons/plecs.c, src/addons/rest.c, test/cpp_api/project.json, test/cpp_api/src/Entity.cpp, test/cpp_api/src/Pairs.cpp, test/cpp_api/src/main.cpp, test/meta/include/meta.h, test/meta/project.json, test/meta/src/DeserializeFromJson.c, test/meta/src/Vars.c, test/meta/src/main.c
This PR adds REST endpoints that make it possible to remotely edit component values and delete entities.
=> Remote editor changes

src/entity.c
This info is useful in observers
=> Provide row in OnSet

flecs.c, flecs.h, include/flecs/addons/cpp/component.hpp, include/flecs/addons/cpp/utils/enum.hpp, include/flecs/addons/flecs_cpp.h, src/addons/flecs_cpp.c
This PR fixes https://github.com/SanderMertens/flecs/issues/940
=> #940 Fix component registration issue with binaries compiled by different compilers

flecs.h, include/flecs/addons/flecs_cpp.h
=> ECS_FUNC_NAME and friends are only relevant to C++

flecs.c, flecs.h, include/flecs.h, include/flecs/private/api_flags.h, include/flecs/private/api_types.h, include/flecs/private/sparse.h, meson.build, src/addons/snapshot.c, src/addons/stats.c, src/bootstrap.c, src/datastructures/entity_index.c, src/datastructures/entity_index.h, src/datastructures/hash.c, src/datastructures/sparse.c, src/entity.c, src/observable.c, src/private_api.h, src/private_types.h, src/table.c, src/world.c, test/addons/src/Stats.c, test/api/src/DeferredActions.c, test/api/src/GlobalComponentIds.c, test/api/src/OnDelete.c, test/api/src/World.c, test/collections/src/Sparse.c
This PR implements the following improvements:
- New entity index data structure with better cache locality
- Replace hash function with wyhash (mostly improves table creation speed)
- Add flag for quick testing if table has name (improves speed of reparenting of entities without name)
=> Performance improvements

docs/DesignWithFlecs.md, docs/FAQ.md, docs/JsonFormat.md, docs/Queries.md, docs/Quickstart.md, docs/Relationships.md, docs/RestApi.md, docs/Systems.md
- Updated documentation links from `flecs.dev` to relative links.
- Fixed broken links.
- Added documentation links where possible.
- Fixed code snippet.
=> Documentation cleanup

include/flecs/addons/flecs_c.h
A trivial change that to fix a source of annoyances in some places.
=> Add a `ecs_singleton_set_ptr`, to mirror `ecs_set_ptr`

docs/Manual.md
Let me know if these small doc fixes are okay for you, I'm not actively looking for errors, just trying to implement them \o
=> [DOCS] Fix `ecs_w_new_pair` in Manual.md

docs/Relationships.md, examples/c/entities/iterate_components/src/main.c, examples/c/prefabs/basics/src/main.c, examples/c/prefabs/override/src/main.c, examples/c/reflection/auto_define_enum/src/main.c, flecs.h, include/flecs.h
I stumbled upon some inaccuracies while learning flecs. I hope this makes things clearer!
=> Misc corrections to the docs

flecs.c, flecs.h, include/flecs/private/api_flags.h, meson.build, src/addons/rules/engine.c, src/addons/rules/rules.h, src/addons/rules/trivial_iter.c, src/bootstrap.c, src/filter.c
Implement dedicated rule iterator for trivial queries.
=> Implement iterator for trivial rule queries

flecs.c, flecs.h, include/flecs.h, include/flecs/addons/cpp/delegate.hpp, include/flecs/addons/cpp/iter.hpp, include/flecs/addons/cpp/lifecycle_traits.hpp, include/flecs/addons/cpp/mixins/alerts/builder_i.hpp, include/flecs/addons/cpp/mixins/term/builder_i.hpp, include/flecs/addons/cpp/utils/enum.hpp, include/flecs/addons/cpp/world.hpp, include/flecs/addons/meta.h, include/flecs/addons/stats.h, include/flecs/addons/system.h, include/flecs/private/api_defines.h, include/flecs/private/sparse.h, src/datastructures/switch_list.c, src/entity.c, src/storage/id_index.h, src/world.c, test/addons/src/MultiTaskThreadStaging.c, test/addons/src/MultiThreadStaging.c
A bunch of minor fixes for typos and selling errors.
=> Fix some typos and spelling errors

flecs.h, include/flecs.h, include/flecs/addons/alerts.h, include/flecs/addons/cpp/entity_view.hpp, include/flecs/addons/cpp/mixins/entity/builder.hpp, include/flecs/addons/cpp/mixins/filter/mixin.inl, include/flecs/addons/cpp/world.hpp, include/flecs/addons/doc.h, include/flecs/addons/expr.h, include/flecs/addons/flecs_c.h, include/flecs/addons/http.h, include/flecs/addons/json.h, include/flecs/addons/log.h, include/flecs/addons/meta.h, include/flecs/addons/metrics.h, include/flecs/addons/module.h, include/flecs/addons/parser.h, include/flecs/addons/system.h, include/flecs/addons/units.h
Use `@code` and `@endcode` markers in the doxygen comments.
Also, use an empty line before code blocks to help ensure they're picked up correctly. When using `@code`...`@endcode` markers, don't indent the code.
=> docs: Use @code/@endcode.

flecs.h, include/flecs/addons/cpp/mixins/doc/impl.hpp, test/custom_builds/cpp/doc/src/main.cpp
Also, fix a copy/paste remnant in `flecs::doc::set_link()`.
=> Add missing `flecs::doc::get/set_color()` functions.

flecs.c, flecs.h, include/flecs.h, include/flecs/addons/http.h, include/flecs/addons/monitor.h, src/addons/http.c, src/addons/meta/definitions.c, src/addons/monitor.c, src/addons/rest.c, src/addons/system/system.c, src/entity.c, src/observer.c, src/private_types.h, src/stage.c, src/stage.h, src/world.c, test/addons/project.json, test/addons/src/Rest.c, test/addons/src/main.c
This PR implements a feature that allows capturing of commands through the REST API, which can be useful during debugging.
=> Command capturing

flecs.c, flecs.h, include/flecs/addons/meta.h
I am having link issues and couldn't find where this function is defined in this project, let me know if I'm not seeing something \o
=> Remove inexistent ecs_meta_set_component

flecs.h, include/flecs/addons/flecs_c.h
This makes it match the rename of `ecs_get_fullpath`.
=> Rename `ecs_get_fullpath_buf` to `ecs_get_path_buf`

docs/ComponentTraits.md, docs/Docs.md, docs/EntitiesComponents.md, docs/FlecsRemoteApi.md, docs/ObserversManual.md, docs/PrefabsManual.md
Corrected a few typos and made minor changes to name casing for the C# documentation snippets.
=> Fix typos and update name cases in C# documentation snippets

docs/Queries.md, flecs.h, include/flecs.h
These were a legacy of v3 and earlier.
=> Fix references to 1-based indexing.

flecs.c, flecs.h, include/flecs/private/api_flags.h, src/entity.c, src/iter.c, src/iter.h, src/query/engine/cache.c, src/query/engine/cache_iter.c, src/query/engine/cache_iter.h, src/query/engine/eval.c, src/query/engine/eval_iter.c, src/query/engine/trivial_iter.c, src/query/engine/trivial_iter.h, src/query/query.h, test/query/src/ChangeDetection.c
This PR improves iterator performance of trivial cached queries.
=> Cached query iterator performance improvements

flecs.c, flecs.h, include/flecs.h, include/flecs/datastructures/allocator.h, include/flecs/private/api_flags.h, src/addons/json/serialize_query_info.c, src/addons/meta/meta.c, src/addons/metrics.c, src/bootstrap.c, src/entity_name.c, src/observer.c, src/query/api.c, src/query/compiler/compiler.c, src/query/engine/cache.c, src/query/engine/cache_iter.c, src/query/engine/eval_iter.c, src/query/types.h, src/query/util.c, src/query/validator.c, src/storage/id_index.c, src/storage/id_index.h, test/core/src/Observer.c, test/core/src/Trigger.c, test/query/project.json, test/query/src/Basic.c, test/query/src/Plan.c, test/query/src/Validator.c, test/query/src/main.c
This PR improves performance of query creation, amongst others by skipping the creation of a query plan for queries that don't need it.
=> Improve query creation performance

flecs.c, src/addons/json/serialize_iter_result_table.c, src/datastructures/block_allocator.c, src/entity.c, src/query/engine/cache_order_by.c, src/query/engine/eval_utils.c, src/query/validator.c, src/storage/table.c, src/storage/table.h, test/core/src/Has.c
This PR improves performance of get, get_mut, has and owns.
=> Improve performance of get, get_mut, has, owns

flecs.h, include/flecs/addons/cpp/mixins/stats/impl.hpp
=> Add missing import to c++ stats module

distr/flecs.c, distr/flecs.h, include/flecs.h, include/flecs/os_api.h, src/addons/pipeline/pipeline.c, src/observer.c, src/query/engine/eval_iter.c
Summary: This diff upstreams a change that fixes thread sanitizer warnings.
Differential Revision:
D62447578
Privacy Context Container: L1120261
=> Fix thread sanitizer warnings, add macro to disable stat counters

.editorconfig, .github/workflows/ci.yml, _typos.toml
Added a CI invocation of https://github.com/crate-ci/typos and configuration for it.
=>  Add CI spell checking using "typos"

docs/Quickstart.md, docs/Systems.md
Routine was renamed to system in
https://github.com/BeanCheeseBurrito/Flecs.NET/releases/tag/v4.0.2
Also update generics usages to valid code after 4.0.2
=> Rename Routine->System in C# docs

distr/flecs.c, distr/flecs.h, include/flecs/addons/cpp/mixins/entity/impl.hpp, include/flecs/addons/cpp/mixins/enum/impl.hpp, include/flecs/addons/cpp/mixins/meta/component.inl, include/flecs/addons/cpp/utils/enum.hpp, include/flecs/addons/flecs_cpp.h, include/flecs/addons/meta.h, src/addons/flecs_cpp.c, src/addons/meta/api.c, src/addons/meta/c_utils.c, src/addons/meta/definitions.c, src/addons/meta/meta.c, test/cpp/project.json, test/cpp/src/Enum.cpp, test/cpp/src/main.cpp, test/meta/project.json, test/meta/src/EnumTypes.c, test/meta/src/main.c
=> Custom underlying enum type

distr/flecs.c, distr/flecs.h, include/flecs/private/api_defines.h, src/os_api.c
=> add cosmo support

examples/build/bazel/README.md
This renovate limitation was fixed by some guy: https://github.com/renovatebot/renovate/pull/33496
=> Minor bazel docs update to reflect improvements in renovate

docs/Quickstart.md
=> Add space to fix bad preview

distr/flecs.c, src/addons/os_api_impl/windows_impl.inl
the memory of cond is not released correctly in windows
=> the memory of cond is not released correctly in windows

distr/flecs.c, src/entity.c, src/entity_name.c, src/storage/ordered_children.c, test/addons/project.json, test/addons/src/MultiThreadStaging.c, test/addons/src/main.c, test/core/src/Monitor.c
Breaking change: https://github.com/SanderMertens/flecs/discussions/466#discussioncomment-13393095
=> Remove support for creating entity ids in multithreaded mode

distr/flecs.h, include/flecs/addons/cpp/utils/utils.hpp
fix amalgamated
Previous pull request: #1709
=> update utils.hpp, fixed amalgamated previous #1709
