include/flecs.h
include/private/flecs.h
include/private/types.h
src/entity.c
src/parser.c
src/system.c
src/table_system.c
src/type.c
src/world.c
test/api/project.json
test/api/src/SystemCascade.c
test/api/src/System_w_FromContainer.c
test/api/src/main.c

With `CASCADE` columns, systems can now easily walk entities in the order of the hierarchy (parent -> child -> grand child etc). A cascade query is created like this:
```
ECS_SYSTEM(world, Transform, Position, TransformMatrix, CASCADE.TransformMatrix);
```
This will walk the entities in the hierarchical order of containers that have the `TransformMatrix` component. When iterating, the cascade column will resolve to the container component as if the system had specified `CONTAINER.TransformMatrix`, or will resolve to `NULL` in case the entity is a root.

Cascade systems

---

src/meson.build

Fixes a few missing commas in the sources list causing meson failures.

Fix source list in src/meson.build

---

include/flecs/flecs.hpp

In https://github.com/SanderMertens/flecs/blob/master/include/flecs/flecs.hpp#L1530 a temporary flecs::world() is constructed from the `m_world` ptr and passed to the [flecs::type() constructor](https://github.com/SanderMertens/flecs/blob/master/include/flecs/flecs.hpp#L743-L759), which only takes a const reference to the passed world object (`const world& world`).
This leads to a dangling reference/pointer bug and in the below example it hits the assert in https://github.com/SanderMertens/flecs/blob/master/src/world.c#L377-L380 because the magic number comes out as garbage (since the world pointer is invalid)
A minimal example (based on the hello world tutorial to reproduce the issue)
```cpp
#include <helloworld.h>
#include <iostream>
int main(int argc, char *argv[]) {
/* Create the …
```

fix dangling reference/ptr to world in entity::type()

---

meson.build

Updated sources, added helloworld executable and `-Dflecs_EXPORTS` when building the library.
Specifies `FLECS_STATIC` for static builds, assuming the `#if` guard is added back into `bake_config.h`, this is needed because static builds should not tag functions with `dllimport/dllexport` in any case.
Adding `target_compile_options(flecs_static PUBLIC "-DFLECS_STATIC")` in the CMakefile would also get rid of link warnings on msvc.
`meson.override_dependency()` allows for `dependency(flecs)` in a superproject without having to specify dependency variable.

Update meson build

---

src/misc.c

Using `Sleep()` 💩 leads to bad 📉📉 frame 🔲🔲  🔲 timing, `CreateWaitableTimer()` is 🈶 much better👌👍🏾.

ecs_os_time_sleep(): use CreateWaitableTimer() on Windows

---

src/strbuf.c

Rename `ecs_strbuf_append_intern()` -> `ecs_strbuf_vappend_intern()`, add `ecs_strbuf_append_intern()` which wraps `ecs_strbuf_vappend_intern()`.
Fixes https://github.com/SanderMertens/flecs/issues/201

strbuf.c: cleanup

---

include/flecs/private/api_defines.h

`COMPILER_GCC` didn't seem to be defined anywhere, this fixed a lot of `-Wunused-variable` warnings with flecs-meta.
Checking for Clang isn't necessary as it also defines `__GNUC__`.

Fix ECS_UNUSED for GCC

---

flecs.c
include/flecs/flecs.hpp

Porting several minor fixes from bleeding edge and combined them in a single PR:
- _*(needs checking)*_ ecs_merge: should assert if world->in_progress == false
- bug: flecs::world move constructor doesn't "steal" from passed in world causing double destruction
- fix: mark single parameter constructors as explicit to prevent incorrect automatic type conversion
- ~~lint: id_no_lifecycle() - default nullptr value for world. Function asserts if its nullptr ergo that's can never be a valid value~~
- fix: entity::set() should not take a const rvalue parameter as that prevents moves

V2 minor fixes

---

include/flecs/flecs.hpp
src/os_api.c
src/world.c

- ecs_os_api_strdup() default implementation incorrectly using default ecs_os_api_malloc
should go through override path
- fix: don't add lifecycle->ctor if other lifecycle fn ptrs are null
registering pod components explicitly should mark lifecycle_set so that in
translation unit B, component_info::id() doesn't override them with
register_lifecycle_actions(true,true,true,true)
- minor: mark world::enable_tracing() as static
it doesn't depend on world and needs to be set to get tracing info from bootstrap init

V2 minor fixes II

---

flecs.h
include/flecs/os_api.h

Unbreak build/usage on FreeBSD systems which don't have alloca.h (but have this function in stdlib.h)

Fix missing alloca() on FreeBSD

---

src/addons/module.c

The import callback was always called before this.

ecs_import(): fix path lookup

---

examples/c/35_empty_system_signature/src/main.c
examples/cpp/35_empty_system_signature/src/main.cpp
flecs.h
include/flecs.h

There is a small typo in examples/c/35_empty_system_signature/src/main.c, examples/cpp/35_empty_system_signature/src/main.cpp, flecs.h, include/flecs.h.
Should read `entities` rather than `entites`.

docs: fix simple typo, entites -> entities

---

include/flecs/flecs.hpp
include/flecs/os_api.h
include/flecs/private/map.h
include/flecs/private/vector.h

- FLECS_PLACEMENT_NEW: personal style choice to make it easy to grep code base for no naked news. Can remove
- Opted for FLECS_NEW/FLECS_DELETE macros as it enables tying of source code location in allocation
- Memory leaks(?): Added FLECS_DELETE but I couldn't find the corresponding calls to free memory that were allocated by new
- Allow ecs_os_* allocation defines to be overridable so users can inject debug info (file/src location tracking)
- minor fix: entity::m_id not initialized to zero
- minor quality of life: replace iostream include with <initializer_list>

fix: use ecs_os_malloc in C++ api. 

---

include/flecs/flecs.hpp

- add `noexcept` to constructors bc stl/3rd party C++ libs sometimes rely on noexcept ctor tags for optimizations (sigh, c++)
- since ctor aren't templates, && isn't treated as perfect forward reference so have to manually have two variants
- changed `call_system` function signatures to take Func&& and placed according std::move/forward
- each/action/iter_invoker calls: add explicit move and const ref ctors
- need to explicitly decay Func template parameter in std::forward invocation

optimization: remove superfluous copies of lambda functions

---

flecs.c
flecs.h
include/flecs.h
include/flecs/flecs.hpp
src/addons/module.c
src/addons/snapshot.c
src/api_support.c
src/bootstrap.c
src/entity.c
src/private_api.h
src/table.c
test/api/src/SystemUnSet.c
test/cpp_api/project.json
test/cpp_api/src/World.cpp
test/cpp_api/src/main.cpp

This PR addresses a number of problems with component registration in C++ that can occur when using multiple worlds, hot reloading of code, and implicit component registration.

Cpp component registration fix

---

include/flecs/flecs.hpp

This is a tiny fix in flecs.hpp, there is an #elif without expression instead of #else

flecs.hpp: fix error #elif with no expression

---

CMakeLists.txt
cmake/target_default_compile_options.cmake
cmake/target_default_compile_warnings.cmake

This PR improves CMake build of flecs:
- add options to build static or shared or both (I would have loved preventing to build both static and shared -because it forces to use 2 different imported targets for shared and static- but since it's already there I can't remove this feature without eventually breaking several downstream projects)
- add an option to enable full warnings
- add an option to disable PIC on non Windows plarforms
- honor `CMAKE_*_FLAGS*` from user
- rely on `C_VISIBILITY_PRESET` property instead of -fvisibility=hidden
- remove invalid warnings options for C
- export targets in `flecs-config.cmake` to be able to consume flecs with `find_package(flecs)`, then `target_link_libraries(myapp flecs::flecs)` or `target_link_libraries(myapp flecs::flecs_static)`. These …

CMake: improvements (honor compiler flags, add several options, fix install and export targets)

---

flecs.c
src/log.c

A simple fix to silence this warning:
```
flecs.c:1312:12: warning: null destination pointer [-Wformat-truncation=]
1312 |      size = vsnprintf(result, ecs_to_size_t(size), fmt, tmpa);
|             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
This warning shows in gcc 10 when using -Wformat option.

Fix warning: null destination pointer

---

include/flecs/private/vector.h

This branch attempts to repair the `flecs::vector::first` and `flecs:vector::last` methods.
closes #359

#359 repair c++ vector.first and .last methods

---

.github/workflows/ci.yml

GitHub removed versions <9 for gcc/clang from virtual environments. Add rules to manually install them in the image.

Update ci.yml to add missing compilers

---

include/flecs/cpp/entity.hpp

If `m_world` is null on a `flecs::entity` then `is_valid()` asserts, which doesn't make any sense on a validity check.  This small PR just returns false for `is_valid()` and `is_alive()` if the `m_world` value is null

Handle a null world in is_valid and is_alive

---

flecs.h
include/flecs.h
include/flecs/cpp/component.hpp
include/flecs/cpp/entity.hpp
include/flecs/cpp/impl.hpp
include/flecs/cpp/impl/lifecycle_traits.hpp
include/flecs/cpp/lifecycle_traits.hpp
include/flecs/cpp/module.hpp
include/flecs/cpp/util.hpp
include/flecs/flecs.hpp
test/cpp_api/include/cpp_api.h
test/cpp_api/project.json
test/cpp_api/src/ComponentLifecycle.cpp
test/cpp_api/src/World.cpp
test/cpp_api/src/main.cpp
test/cpp_api/src/util.cpp

This PR enables using types as components that are not default constructible and are not copyable. Types must still be movable and destructible.
The details of what changed:
- non-default constructible types can be registered as components
- non copyable (either with a deleted copy ctor, copy assignment or both) can be registered as components
- when a type has a `T(flecs::world&, flecs::entity)` ctor, the C++ API will use this instead of the default ctor
- types that are not movable or destructible will throw static asserts upon registration/first usage
- when a non-default constructible type is used with add a static assert is thrown
- when a non-default constructible type is set, the first set move constructs, subsequent calls move assign
fixes #419

Component lifecycle improvements

---

docs/Manual.md
docs/Relations.md
flecs.h
include/flecs.h
include/flecs/addons/deprecated/iter.hpp
include/flecs/cpp/builder.hpp
include/flecs/cpp/component.hpp
include/flecs/cpp/entity.hpp
include/flecs/cpp/function_traits.hpp
include/flecs/cpp/impl/entity.hpp
include/flecs/cpp/impl/iter.hpp
include/flecs/cpp/impl/world.hpp
include/flecs/cpp/invoker.hpp
include/flecs/cpp/iter.hpp
include/flecs/cpp/lifecycle_traits.hpp
include/flecs/cpp/pair.hpp
include/flecs/cpp/query.hpp
include/flecs/cpp/util.hpp
include/flecs/cpp/world.hpp
include/flecs/flecs.hpp
test/cpp_api/project.json
test/cpp_api/src/ComponentLifecycle.cpp
test/cpp_api/src/Entity.cpp
test/cpp_api/src/Pairs.cpp
test/cpp_api/src/main.cpp

This PR cleans up a lot of the template code in the C++ API and adds a manual for entity relationships. A few new features are introduced:
A `pair` template was used to the C++ API that can be used in place of specifying both types for a pair:
```cpp
struct Eats {
float amount;
};
struct Apples { };
struct Pears { };
using EatsApples = flecs::pair<Eats, Apples>;
using EatsPears = flecs::pair<Eats, Pears>;
auto e = ecs.entity()
.set<EatsApples>({ 10 })
.set<EatsPears>({ 20 });
// Using a pair type is equivalent to specifying the types separately:
e.has<Eats, Apples>(); // true
e.has<Eats, Pears>(); // true
// Pair types can be used with function-style set/get operations:
e.get([](const EatsPears& p) {
std::cout << "Eats pears: " << p->amount << std::endl;
});
```
A match function was added …

#124 cleanup C++ API, docs

---

examples/os_api/flecs-os_api-stdcpp/src/flecs-os_api-stdcpp.cpp

reinterpret cast the int32_t into a long because of compiler and language guff
to be clear stdint.h guarantees that int32_t is always a 32 bit int but in C specs a int and a long can have different value sizes (even though that is rarely the case) so to please MSVC we need to reinterpret_case int32_t into a Long (for some reason, blame MSVC not me)

Add support for atomic increment/decrement to stdcpp OS API example

---

include/flecs/cpp/entity.hpp

This PR introduces `operator bool` to `flecs::entity` which prevents `flecs::id`'s `operator flecs::id_t` from being used in conditional expressions (which is error-prone as it translates to a simple m_id != 0). See https://github.com/SanderMertens/flecs/issues/428 for more details.
On the user level this code (which compiles even without this PR) now makes much more sense:
```c++
// State.SelectedChunk is a flecs::entity_view.
if (State.SelectedChunk) {
auto &Chunk = *State.SelectedChunk.mut(ECS).get_mut<CTileChunk>();
auto &Tile = Chunk.Tiles[State.SelectedChunkTileIndex.X][State.SelectedChunkTileIndex.Y];
Tile.Walkable = !Tile.Walkable;
}
```
Before this PR it did not check for the aliveness of the entity, neither did it check for the existence of the world.
With this PR, this code is …

#428 Improvements on the bool conversion of entities

---

flecs.c
src/filter.c

Little fix for this warning
```
flecs.c: In function ‘ecs_filter_str’:
flecs.c:17107:36: warning: duplicated ‘if’ condition [-Wduplicated-cond]
17107 |             } else if (term->inout == EcsInOut) {            
|                        ~~~~~~~~~~~~^~~~~~~~~~~
/home/aganm/Projects/gow/lib/flecs/flecs.c:17105:36: note: previously used here
17105 |             } else if (term->inout == EcsInOut) {
```

Fix duplicate cond

---

include/flecs/private/api_defines.h

This was a breaking change for flecs-meta which utilizes ECS_UNUSED for globals, part of 4aade63c13985a0933f975082fc63b90ef6f0e4c.

Revert changes to ECS_UNUSED

---

include/flecs/cpp/entity.hpp

Made `entity` and `entity_view` default constructors implicit.
See #461 for more details.

#461 make entity and entity_view implicitly default constructible

---

src/datastructures/hash.c

Fixes building when user has defined `VALGRIND` and tries to build a debug build, for
compilers that do not allow `VALGRIND` to be defined twice. Also adds support for address sanitizer's
most common warding define.

Update hash.c to allow valgrind to always be defined, and support address sanitizer

---

flecs.c
flecs.h
include/flecs.h
include/flecs/addons/cpp/world.hpp
include/flecs/addons/flecs_c.h
src/entity.c
src/private_api.h
src/private_types.h
src/stage.c
test/api/project.json
test/api/src/DeferredActions.c
test/api/src/OnDelete.c
test/api/src/main.c
test/cpp_api/project.json
test/cpp_api/src/World.cpp
test/cpp_api/src/main.cpp

This PR adds the `delete_with` (delete all entities with id) and `remove_all` (remove all instances of id) functions, in addition to a new deferred operation that enables the operations to be called from a stage.

Add delete_with, remove_all functions

---

docs/Quickstart.md

Was reading through the Quickstart and discovered a minor bug in the System C++ example.

[doc] Add missing for loop in System C++ example in Quickstart

---

flecs.c
flecs.h
include/flecs/addons/app.h
include/flecs/addons/cpp/mixins/system/builder_i.hpp
include/flecs/addons/system.h
src/addons/app.c
src/addons/http.c
src/addons/pipeline/pipeline.c
src/addons/pipeline/pipeline.h
src/addons/pipeline/worker.c
src/addons/rest.c
src/addons/system/system.c
src/addons/system/system.h
src/entity.c
test/api/project.json
test/api/src/MultiThread.c
test/api/src/MultiThreadStaging.c
test/api/src/Pipeline.c
test/api/src/Stresstests.c
test/api/src/main.c

This PR introduces 2 new features:
- Single threaded systems (now the default). Systems can be made multithreaded by explicitly setting the `multi_threaded` parameter to `true`
- Unstaged systems. Systems can be made unstaged by explicitly setting the `no_staging` parameter to `true`.
The PR also fixes an issue where the pipeline schedule would get confused in multithreaded mode when systems would be added/removed while progressing a frame.
Fixes #389 
Fixes #543

Pipeline improvements

---

docs/Relations.md

A lambda callback was missing its open parentheses.

Fix typo in "relations" docs

---

flecs.c
flecs.h
include/flecs.h
include/flecs/addons/cpp/component.hpp
include/flecs/addons/cpp/mixins/query/impl.hpp
include/flecs/private/api_types.h
src/addons/rules.c
src/addons/snapshot.c
src/addons/system/system.c
src/filter.c
src/iter.c
src/query.c
test/api/include/api.h
test/api/project.json
test/api/src/Filter.c
test/api/src/Iter.c
test/api/src/MultiThread.c
test/api/src/Query.c
test/api/src/Rules.c
test/api/src/main.c
test/api/src/util.c

This adds the ability to create paged / worker iterators from any source. Previous to this change only query iterators could be paged (using offset/limit) and used on multiple threads (using `ecs_query_next_worker`).
See here for more details: https://github.com/SanderMertens/flecs/discussions/466#discussioncomment-1775633

#124 implement chained page & worker iterators

---

flecs.c
src/addons/http.c
src/os_api.c

Currently flecs is not compiled correctly on Windows if we aren't using MSVC compiler. This pull request adds appropriate #if defined _WIN32 and !defined where needed to support correct socket headers on mingw + GCC

Fixed compile errors due to referring to Unix sockets instead of Winsock on Windows with mingw and GCC

---

include/flecs.h
include/flecs/private/sparse.h
src/world.c

implements #587
Use case example (sorry for custom syntax):
```c
entity CreateEntity(ecs &ECS, FStringView Name, EEntityKind Kind) {
// We do not recycle ids because it allows us to preserve creation order during serialization even in single-threaded mode (unlike flecs).
// For temporary entities we travel between N ranges of entities to avoid locks yet reuse ids.
uint64 Id;
if(Kind == EEntityKind::Persistent) {
Id = Impl::PersistentEntityIdCounter.fetch_add(1, std::memory_order_relaxed);
} else {
Check(Kind == EEntityKind::Temporary);
Id = Impl::TemporaryEntityIdCounter.fetch_add(1, std::memory_order_relaxed);
Checkf(Id < Impl::TemporaryEntityIdCurrentFrameEnd, "Temporary entity overflow");
auto OldId = Id | ((Impl::TemporaryEntityIdLoopCounter - 1) << …
```

Added ecs_set_entity_generation

---

include/flecs/addons/cpp/component.hpp

When compiling with MSVC in Visual Studio or Rider for Unreal it complains about 'assignment within conditional expression' (C4706 warning):
`while ((ptr = strstr(ptr + 1, "struct "))) { }`
To fix this issue we need to explicitly test the result of the assignment:
`while ((ptr = strstr(ptr + 1, "struct ")) != 0) { }`

Fixing C4706 MSVC warning: assignment within conditional expression

---

flecs.c
flecs.h
include/flecs/addons/cpp/c_types.hpp
include/flecs/addons/cpp/flecs.hpp
include/flecs/addons/cpp/impl/iter.hpp
include/flecs/addons/cpp/iter.hpp
include/flecs/addons/cpp/mixins/filter/builder_i.hpp
include/flecs/addons/cpp/mixins/rule/builder.hpp
include/flecs/addons/cpp/mixins/rule/decl.hpp
include/flecs/addons/cpp/mixins/rule/impl.hpp
include/flecs/addons/cpp/mixins/rule/mixin.inl
include/flecs/addons/cpp/mixins/term/builder_i.hpp
include/flecs/addons/cpp/mixins/term/impl.hpp
include/flecs/addons/cpp/utils/iterable.hpp
include/flecs/addons/cpp/world.hpp
include/flecs/addons/rules.h
src/addons/rules.c
src/filter.c
test/api/include/api/bake_config.h
test/cpp_api/project.json
test/cpp_api/src/RuleBuilder.cpp
test/cpp_api/src/main.cpp

This PR adds support for the rules addon to the C++ API. The API reuses the same builder/iteration functions as filters & queries, but with the additional ability to use query variables:
```c
// Create query for (Eats, *)
auto r = world.rule_builder()
.term(Eats).obj("_Food"); // _ means "Food" is a query variable
.build();
// Anyone who eats anything
r.each([](flecs::iter& it, int index) {
cout << "Entity " << it.entity(index).name()
<< "Eats " << it.get_var("Food").name() << "\n";
});
// Anyone who eats apples
r.iter()
.set_var("Food", Apples)
.each([](flecs::iter& it, int index) { /* .. */ });
// Anyone who eats pears
r.iter()
.set_var("Food", Pears)
.each([](flecs::iter& it, int index) { /* .. */ });
```

Add C++ rules API

---

flecs.c
flecs.h
include/flecs/addons/rules.h
src/addons/rules.c
test/api/project.json
test/api/src/Rules.c
test/api/src/main.c

This PR introduces a change that makes it possible to set variables that are resolved as table by the rule engine.

Add support for setting table variables on rule iterators

---

docs/Relations.md
flecs.c
flecs.h
include/flecs.h
include/flecs/addons/cpp/c_types.hpp
include/flecs/addons/log.h
include/flecs/private/api_defines.h
src/addons/log.c
src/bootstrap.c
src/datastructures/map.c
src/entity.c
src/hierarchy.c
src/private_api.h
src/private_types.h
src/search.c
src/world.c
test/api/project.json
test/api/src/Pairs.c
test/api/src/main.c

This PR improves the performance of searching for components by following a relationship. It also introduces a new `DontInherit` policy that prevents components from being inherited from base entities (`IsA` targets). This new property replaces the builtin behavior for the `Prefab`, `Disabled`, `Identifier` and `ChildOf` components.
This PR is part of implementing #632

Improved relation search

---

flecs.c
flecs.h
include/flecs.h
include/flecs/os_api.h
src/addons/rules.c
src/datastructures/sparse.c
src/entity.c
src/filter.c
src/observable.c
src/private_api.h
src/private_types.h
src/query.c
src/stage.c
src/table.c
src/table_cache.c
src/table_cache.h
src/world.c
test/api/include/api/bake_config.h
test/api/src/Filter.c
test/api/src/Observer.c
test/api/src/Pipeline.c
test/api/src/Switch.c
test/api/src/SystemManual.c
test/api/src/SystemMisc.c
test/api/src/Trigger.c

This PR implements a change that delays emitting table empty events until the administration is required to be consistent (for example, when evaluating a query). In practice this reduces the number of emitted events as well as the frequency with which tables are removed between empty and non-empty lists, which can significantly improve performance of `add` operations.
For reference, this is a simple add benchmark before the change (lower is better):
```md
new w/tag:          37.08ns
add 16 tags:        472.88ns (avg)
delete_with:        9.04ns (per entity)
```
The same benchmark after the change:
```md
new w/tag:          37.48ns
add 16 tags:        33.19ns (avg)
delete_with:        9.62ns (per entity)
```
In the first benchmark, the events generated by each table empty/non-empty …

Delayed table events

---

CMakeLists.txt

Howdy!
I have been working with flecs via conan and so I've started using CMake again. After setting up a recipe for flecs v3 I noticed that *.inl files don't get installed.

Install *.inl files with headers.

---

README.md

- Updated the "Relations Manual" link in `README.md` to point to `docs/Relations.md` instead of `docs/Queries.md`

Fixed 'Relations' link in README.md

---

docs/Quickstart.md

- Renamed `*PostStore` to `*OnStore` for both C/C++ doc
- Removed `flecs::PostValidate` from C++ doc
- Moved `flecs::PostUpdate` after `flecs::OnValidate` in C++ doc
@SanderMertens Is it intended that the phases `PreFrame` and `PostFrame` are not mentioned? Or should they be added to the documentation?

Updated Pipeline tags in Quickstart.md

---

docs/Quickstart.md

- Wrote sub-section "Custom Pipeline" in Quickstart.md
Following the comment you made [here](https://github.com/SanderMertens/flecs/pull/654#issuecomment-1048515449), I thought this was appropriate to add a section regarding custom pipelines.
I encountered an issue where I was using a custom pipeline without `PreFrame`/`PostFrame` tags, and when I was trying to enable the REST interface for the flecs explorer, it wasn't working.

Wrote "Custom Pipeline" sub-section for Quickstart manual

---

flecs.c
flecs.h
include/flecs.h
include/flecs/private/api_types.h
src/filter.c
src/iter.c
test/api/project.json
test/api/src/Filter.c
test/api/src/main.c

This PR adds the ability to set a value for the `This` variable of a filter iterator to a table. This restricts the results of the iterator to the table, and can be used to check whether a table matches with a filter, and with which ids. If a filter contains a wildcard, the iterator will, just like a regular iterator, return a result for each matching column.
This feature will eventually get expanded to the ability to specify entity variables (allowing the iterator to match with a single entity) and the ability to use filters with more than one variable.
Example:
```c
// (Likes, *)
ecs_filter_t f;
ecs_filter_init(world, &f, &(ecs_filter_desc_t){
.terms = {
{ ecs_pair(Likes, EcsWildcard) }
}
});
// Find id for This variable
int var_id = ecs_filter_find_this_var(&f);
// Create iterator & …
```

Add support for setting query variables on filter iterator

---

flecs.c
src/addons/os_api_impl/os_api_impl.c

I manually modified `flecs.c` since bake-amalgamate doesn't currently work on Windows.

Issue 677 - Use Windows os_api_impl on non-MSVC Windows Targets

---

flecs.c
flecs.h
include/flecs.h
include/flecs/addons/cpp/mixins/pipeline/impl.hpp
include/flecs/addons/cpp/mixins/pipeline/mixin.inl
include/flecs/addons/cpp/world.hpp
src/addons/pipeline/pipeline.c
src/addons/pipeline/worker.c
src/entity.c
src/private_types.h
src/stage.c
src/world.c
test/addons/src/MultiThreadStaging.c
test/addons/src/Snapshot.c
test/addons/src/SystemManual.c
test/api/project.json
test/api/src/DeferredActions.c
test/api/src/Entity.c
test/api/src/Event.c
test/api/src/Filter.c
test/api/src/Get_component.c
test/api/src/Lookup.c
test/api/src/Query.c
test/api/src/SingleThreadStaging.c
test/api/src/World.c
test/api/src/main.c
test/cpp_api/src/Entity.cpp
test/cpp_api/src/Enum.cpp
test/cpp_api/src/Event.cpp
test/cpp_api/src/World.cpp

This PR improves staging usability, and prevents throwing readonly asserts in single-threaded applications. For more details, see: https://github.com/SanderMertens/flecs/discussions/466

Staging improvements

---

CMakeLists.txt

Mingw clang throws linker errors from `addons/http.c` due to not implicitly linking the winsock libs. Explicitly linking them in flecs' CMake fixed the issue.
CI passed on my fork (unsurprisingly).

Fix win clang linker errors (link winsock explicitly)

---

flecs.c
flecs.h
meson.build
src/datastructures/stack_allocator.c
src/datastructures/stack_allocator.h
src/entity.c
src/observer.c
src/private_api.h
src/private_types.h
src/stage.c
test/api/project.json
test/api/src/DeferredActions.c
test/api/src/Set.c
test/api/src/main.c

Improve performance of deferred `set` and `get_mut` operations by using a stack allocator for temporary component values.

Implement stack allocator for deferred ops

---

README.md
docs/DesignWithFlecs.md
docs/FAQ.md
docs/JsonFormat.md
docs/Manual.md
docs/Queries.md
docs/Quickstart.md
docs/Relations.md
docs/RestApi.md
examples/c/entities/hooks/src/main.c
examples/c/rules/component_inheritance/src/main.c
flecs.c
flecs.h
include/flecs.h
include/flecs/addons/flecs_c.h
include/flecs/addons/log.h
include/flecs/addons/meta_c.h
include/flecs/os_api.h
include/flecs/private/addons.h
include/flecs/private/api_defines.h
include/flecs/private/vector.h
src/addons/meta/cursor.c
src/addons/meta_c.c
src/datastructures/entity_index.h
src/iter.c

- Fixed typos, trailing whitespaces, styling inconsistencies all over the documentation, readme and even some comments (in case of "macro's") specifically;
- Emphasized Flecs' unique features more by moving the hierarchies and relations up the key features list in README and adding another sentence highlighting the core design to brief description;
- Brought back the building and usage mini-section from manual (it wasn't intuitive for it to be there, usually such info is placed on project README);
- Removed the addons section from manual as it a) overlaps with the README one, b) seems to be way outdated from a quick glance on blame and the codebase.

Improve documentation and readme

---

src/addons/http.c
src/addons/os_api_impl/windows_impl.inl

Hello! This PR makes it possible to compile Flecs using MinGW (since MinGW's own compiler, GCC, is case-sensitive regarding header names).

Fix Windows headers case to make MinGW compiler happy

---

docs/Queries.md

The `Operator Overview` table in `Queries.md` doesn't render properly because of `|`.
When writing a pipe in a code block, it needs to be espaced with `\` as per the [GFM spec](https://github.github.com/gfm/#example-200).
- Escaped `|` in the `Operator Overview` table to render them properly 
Before
After

Fix pipe rendering in Queries.md

---

flecs.h
include/flecs/addons/cpp/utils/enum.hpp
include/flecs/os_api.h

This PR fixes two issues:
- use mingw vsprintf implementation
- enum constant name detection failed due to different `size_t` string in `__PRETTY_FUNCTION__` on Windows

Mingw fixes

---

flecs.c
flecs.h
include/flecs/private/block_allocator.h
include/flecs/private/vec.h
src/datastructures/vec.c
src/entity.c
src/private_types.h
src/stage.c
src/stage.h
src/table.c
src/table.h
src/table_graph.c
src/world.c
src/world.h
test/api/project.json
test/api/src/ComponentLifecycle.c
test/api/src/DeferredActions.c
test/api/src/main.c

This PR implements command batching, which is an optimization that for many situations limits the number of archetype moves for an entity to 1, even when N commands are enqueued for an entity.
Batching happens for operations that are enqueued while the world is in deferred mode.

Command batching

---

flecs.c
flecs.h
include/flecs.h
src/addons/expr/deserialize.c
src/addons/flecs_cpp.c
src/addons/rules.c
src/datastructures/stack_allocator.c
src/entity.c
src/filter.c
src/iter.c
src/private_types.h
src/query.c
src/world.c
test/addons/project.json
test/addons/src/Plecs.c
test/addons/src/main.c
test/api/project.json
test/api/src/Filter.c
test/api/src/Query.c
test/api/src/main.c
test/cpp_api/project.json
test/cpp_api/src/Entity.cpp
test/cpp_api/src/main.cpp

This PR adds features fixes bugs and improves performance when working with queries
- Fixed issue that caused unnecessary lookups when using `ecs_ref_t`
- Add `ecs_query_next_table` function that only populates `ecs_iter_t::table` to improve iteration speed
- Add `ecs_query_populate` function to conditionally populate iterator data after `ecs_query_next_table`
- Improve performance of query change detection
- Fix assert when using change detection with query that has fixed source term
Additionally these non-query related issues were fixed:
- Fixed issue in plecs where a number followed by a newline and `-` was be interpreted as binary expression
- Fixed issue where overriding a prefab child associated with a type would assert
- Removed redundant call to `ecs_time_measure`

Query improvements & bugfixes

---

include/flecs/private/api_support.h

Allow defining custom ECS_HI_COMPONENT_ID value without the "macro redefined" warnings (which are errors with pedantic compilation).

Lazy definition of ECS_HI_COMPONENT_ID (23.09 22:42)

---

flecs.c
flecs.h
include/flecs.h
include/flecs/addons/stats.h
include/flecs/os_api.h
include/flecs/private/allocator.h
src/addons/os_api_impl/posix_impl.inl
src/addons/os_api_impl/windows_impl.inl
src/addons/rest.c
src/addons/stats.c
src/datastructures/block_allocator.c
src/datastructures/map.c
src/datastructures/stack_allocator.c
src/entity.c
src/os_api.c
src/table.c
src/table_cache.c
test/api/project.json
test/api/src/DeferredActions.c
test/api/src/Internals.c
test/api/src/main.c

This PR fixes a memory leak that occurred during cleanup of a map. The leak was introduced by the allocator PR (https://github.com/SanderMertens/flecs/pull/805) and caused a map to not free memory if it used a shared allocator.
The PR also adds new statistics for allocators, and a `FLECS_ACCURATE_COUNTS` define that, when enabled, ensures that allocation counts are correct in multithreaded applications.

Fix memory leak, improve memory statistics

---

include/flecs.h

Allows defining custom ECS_ID_CACHE_SIZE without compilation errors

Support for custom ECS_ID_CACHE_SIZE define

---

include/flecs/private/addons.h

If you have both defines FLECS_MONITOR and FLECS_STATS , it generates a warning for FLECS_STATS redefinition, this PR fixes it.

Fix define redifinition monitor

---

.github/workflows/ci.yml
include/flecs/addons/cpp/utils/enum.hpp
include/flecs/private/api_defines.h
test/cpp_api/project.json
test/cpp_api/src/PrettyFunction.cpp
test/cpp_api/src/main.cpp

This PR fixes enum reflection for Apple Clang 14 by making sure the `__PRETTY_FUNCTION__` macro is interpreted correctly. The PR also adds jobs to CI that runs the C++ test suite against different compiler versions for both clang and gcc.

Fix enum reflection for Apple Clang 14

---

docs/Queries.md

This PR updates Queries.md to include a mention to the new C++ API methods added in the commit 5c54bbd731c04ac8fb9fa950904b47a5e8a97a71 which are `with`/`without`/`read`/`write`.
- Fixed typos in docs/Queries.md;
- Added table for new C++ API methods in the "Query Creation" section in docs/Queries.md.

Add mention to new C++ API query methods in Queries.md

---

CMakeLists.txt

Made the CMake project generate the same folder structure in Visual Studio (and probably other IDEs) as is used on disk.
This makes it easier to reason about which file is which and to find the files in the solution explorer

Create the same folder structure in Visual Studio as on disk

---

BUILD

I couldn't get building with Bazel to work due to `.inl` file not found errors. This seems like the necessary fix though I'm only just starting to get to grips with Bazel so please let me know if there's an alternative.

Update BUILD to support .inl files in Bazel builds

---

docs/Queries.md

On my machine using MSVC I had to change the parameter types to `flecs::entity_t` here in order for it to compile.
I am not certain if the C++ API functor signature should be changed, if these documentations should be updated, or if I set it up incorrectly.
```
error C2664: 'Base &flecs::query_builder_i<Base>::order_by(flecs::entity_t,int (__cdecl *)(flecs::entity_t,const void *,flecs::entity_t,const void *))': cannot convert argument 2 from 'M::Pipeline::{ctor}::<lambda_1>' to 'int (__cdecl *)(flecs::entity_t,const void 
*,flecs::entity_t,const void *)'
```

`flecs::entity_t` vs `flecs::entity`

---

src/addons/system/system.c

I have changed `ecs_float_t` to `double` on my configuration. Spares me from
```cpp
cxx/lib/flecs/src/addons/system/system.c:124:33: warning: implicit conversion from ‘float’ to ‘double’ to match other operand of binary expression [-Wdouble-promotion]
124 |         system_data->time_spent += (float)ecs_time_measure(&time_start);
|                                 ^~
```
(GCC)

Use `ecs_ftime_t`

---

include/flecs/addons/cpp/entity_view.hpp

If I can do `entity.has ( flecs::Disabled )` from a const entity, shouldn't these also be const?

Intentially non-const?

---

include/flecs/addons/module.h

I ran into this by chance when trying to parse `#define`s from the header file directly. Seems to be the only place an extra `\` character is at the end of a macro, so likely unintentional.

Remove unnecessary backslash in ECS_MODULE macro

---

include/flecs.h

I found `is_monitor` is the only place that, for some reason, uses `**<` on subsequent lines of a multi-line comment. I changed it to match the others.

Match comment on is_monitor with other multi-line comments

---

include/flecs/addons/cpp/utils/enum.hpp

Fix compilation error with the latest emscripten em++:
```
../subprojects/flecs/include/flecs/private/../addons/cpp/utils/enum.hpp:23:30: error: integer value 128 is outside the valid range of values [0, 7] for this enumeration type [-Wenum-constexpr-conversion]
static constexpr E value = static_cast<E>(Value);
```
Searching around in github I found the solution in the magic_enum project and adapted it.

Fix clang compilation error

---

.editorconfig
include/flecs.h
include/flecs/addons/cpp/world.hpp
include/flecs/addons/http.h
include/flecs/addons/json.h
include/flecs/addons/meta.h
include/flecs/addons/module.h
include/flecs/addons/stats.h
include/flecs/addons/system.h

These are a couple of things that I came across while digging through comments.
- ~~Removing trailing whitespace seems like a good idea. In some cases in the code is used to indent a line with the next one that has code or comments on it, but it's pretty inconsistent. There are also plenty of places where additional spacing was left in accidentally. (This is done for the entire repository, not just source files.)~~ (Removed on request.)
- Some comments were documentation comments where it did not make sense. Maybe they could be converted to group / header comments for doxygen - unsure how that works - but I just turned them into regular comments for now.
- In a couple of places have comments where it seems like it would make sense for them to be documentation comments instead.
- I took …

Documentation comments and style suggestions

---

src/table.c
test/cpp_api/project.json
test/cpp_api/src/ComponentLifecycle.cpp
test/cpp_api/src/main.cpp

Fixes an issue that happens when the world is destructed (and maybe other cases too).
In the case the column was merged into a non-empty column, the old column's data (after being moved out) was freed but never had the destructor called on it leaking memory with some types.

Fix the destructor not being called when a column is merged

---

examples/cpp/systems/custom_phases_no_builtin/src/main.cpp

The expected output for this example is: 
system GameSystem
system PhysicsSystem
system CollisionSystem
However the current output is:
system PhysicsSystem
system CollisionSystem
system GameSystem
From looking at the C version of this example, GameSystem is supposed to be of kind Update and not flecs::OnUpdate. Swapping out that one line allows the expected and actual output to match.

Fix phase error in custom_phases_no_builtin cpp example

---

docs/Quickstart.md

Noticed this while reading the docs. I assume it's an unintentional copy-paste?
EDIT: I re-read and realized it was probably supposed to be 2 different ways of adding components, not one continuous code example. I added some comments to clarify that instead of removing the `auto` declaration.

[docs] Fix conflicting declaration

---

src/addons/meta/cursor.c

Before this fix if you passed e.g. `-1` to set an U64 it will fail, but all values are valid for an U64. It will still error out for U32/16/8 with a value of `-1` but I think that's fair.

ecs_meta_set_int(): fix unsigned bounds check

---

flecs.c
flecs.h
include/flecs.h
src/datastructures/block_allocator.c
src/entity.c
src/entity_filter.c
src/filter.c
src/iter.c
src/private_types.h
src/query.c
src/table.c

This PR implements the following improvements:
- Reduce overhead of tables without unions/bitsets/relationship flattening
- Avoid repeated lookups for checking tags on term ids
- Use single allocation for terms/sizes array where possible
- Add `ecs_table_has_id` function
- Fix crash where wildcard id record could be deleted before matching non-wildcard id record
- Fix crash where during world fini a filter decreases refcount after id record is deleted

Filter creation performance improvements

---

flecs.h
include/flecs/addons/cpp/mixins/rule/impl.hpp

Noticed the `str` method for rules wasn't `const` so went to fix that and noticed in the process that it was calling the filter string method instead of the new one for rules so I've also changed it to that whilst also adding a method to get the filter so the old string result can still be fetched.
This is a breaking change however from the previous behavior though due to the output being very different so it might be better to add a different method to return the rule string?

Add a way to get the filter from a rule, swap str method to rule specific one

---

docs/Relationships.md
flecs.c
flecs.h
include/flecs.h
include/flecs/private/api_support.h
include/flecs/private/sparse.h
src/addons/json/deserialize.c
src/datastructures/allocator.c
src/datastructures/block_allocator.c
src/datastructures/sparse.c
src/entity.c
src/id_record.c
src/stage.c
src/table_graph.c
src/world.c
test/api/src/Entity.c
test/api/src/New.c
test/cpp_api/src/World.cpp

This PR adds a `FLECS_LOW_FOOTPRINT` flag that sets a number of constants which favor low memory utilization over speed.

Add low footprint mode

---

flecs.c
src/addons/os_api_impl/posix_impl.inl

Made for TCC but that should also work for every system/compiler without the gnu builtins.

Emulate posix atomics for systems that do not have gnu built-ins

---

.github/workflows/ci.yml
examples/cpp/game_mechanics/scene_management/src/main.cpp

Add the following targets to CI:
- vs2017
- clang (Windows)

Add legacy visual studio versions to CI

---

src/addons/rules/compile.c

- I did not touch the main `flecs.c`.
- May want to add tests like you did for `ecs_rule_var_count`.
- I took the liberty of moving `ecs_rule_var_count` so all functions appear in the same order as in `rules.h`.
- Code taken from [rules.c of commit `5043840`](https://github.com/SanderMertens/flecs/blob/50438400bfae1dcc2aba343c6eba98b04bad485e/src/addons/rules.c#L2914C47-L2928).
- Simply changed `EcsRuleVarKindEntity` to `EcsVarEntity`.
- Compiled, tested in my project, solved the issue with missing functions I had.
Welcome back, Inspector Gadget.

Add missing ecs_rule_var_name and ecs_rule_var_is_entity

---

src/hierarchy.c

This appears to be unnecessary because `ecs_add_path_w_sep` already does the same thing.

Remove sep initialization in ecs_new_from_path_w_sep

---

include/flecs/addons/cpp/utils/iterable.hpp

`each_invoker` passes a `size_t` not a `int32_t`
See: https://github.com/SanderMertens/flecs/blob/c8f946b1daa6571cc1839f779574368562ee9402/include/flecs/addons/cpp/invoker.hpp#L290-L293

Fix comment on iterable::each

---

meson.build

With MSVC `#pragma comment(lib, "ws2_32.lib")` is enough, but mingw doesn't support that.
Build error initially reported here https://github.com/flecs-hub/flecs-lua/issues/12
@MasterDrake can you confirm the fix?

meson: link ws2_32 for mingw builds

---

include/flecs/private/hashmap.h

I used some features of flecs in my program, and I noticed a small mistake in the parameter naming. as follows:
`#define flecs_hashmap_init(hm, K, V, compare, hash, allocator)\ 
_flecs_hashmap_init(hm, ECS_SIZEOF(K), ECS_SIZEOF(V), compare, hash, allocator)`
`#define flecs_hashmap_init(hm, K, V, hash, compare, allocator)\ 
_flecs_hashmap_init(hm, ECS_SIZEOF(K), ECS_SIZEOF(V), hash, compare, allocator)`

a small mistake in the parameter naming

---

docs/Queries.md
flecs.c
flecs.h
include/flecs.h
include/flecs/addons/cpp/c_types.hpp
include/flecs/addons/cpp/mixins/filter/builder_i.hpp
include/flecs/private/api_flags.h
src/addons/alerts.c
src/addons/json/serialize.c
src/addons/parser.c
src/addons/rules/compile.c
src/addons/rules/rules.h
src/bootstrap.c
src/filter.c
src/world.c
test/addons/project.json
test/addons/src/Alerts.c
test/addons/src/Parser.c
test/addons/src/RulesScopes.c
test/addons/src/RulesVariables.c
test/addons/src/main.c
test/api/project.json
test/api/src/FilterStr.c
test/api/src/main.c
test/cpp_api/project.json
test/cpp_api/src/RuleBuilder.cpp
test/cpp_api/src/main.cpp
test/meta/project.json
test/meta/src/SerializeToJson.c
test/meta/src/main.c

This PR implements query scopes, which allows for grouping a set of terms in a query in a "scope", to which query operators can be applied. A query scope is created using curly brackets in the query DSL. An example:
```
Position, !{Velocity || Speed}
```
Some limitations still apply to how query scopes can be used, see the query manual for details.
This PR also includes the following changes:
- Fix issue in rule engine with anonymous source variables and component terms
- Fix issue with JSON serialization of query without `$this` source while alert module is imported
- Fix naming inconsistency between alerts/metrics addon

Query scopes

---

flecs.c
flecs.h
include/flecs/addons/alerts.h
include/flecs/addons/cpp/mixins/alerts/builder_i.hpp
src/addons/alerts.c
src/addons/json/serialize.c
test/addons/project.json
test/addons/src/Alerts.c
test/addons/src/main.c
test/cpp_api/project.json
test/cpp_api/src/Misc.cpp
test/cpp_api/src/main.cpp
test/meta/project.json
test/meta/src/SerializeToJson.c
test/meta/src/main.c

This PR adds the ability to generate alerts from members with values that are out of range. For example:
```cpp
ecs.component<CpuUtilization>()
.member<float>("value")
.warning_range(0, 70)
.error_range(0, 80);
ecs.alert("high_cpu")
.with<CpuUtilization>()
.message("$this has high CPU utilization")
.member<CpuUtilization>("value")
.build();
ecs.entity().set<CpuUtilization>({ 75 }); // throws alert with severity Warning
ecs.entity().set<CpuUtilization>({ 85 }); // throws alert with severity Error
```

Member range alerts

---

src/addons/http.c

https://man.freebsd.org/cgi/man.cgi
https://github.com/leostratus/netinet/blob/master/in.h
Should fix compilation errors on FreeBSD:
```
1176:53: error: use of undeclared identifier 'IPPROTO_TCP'
sock = socket(addr->sa_family, SOCK_STREAM, IPPROTO_TCP);
^
/root/.xmake/cache/packages/2306/f/flecs/v3.2.4/source/src/addons/http.c:1193:34: error: use of undeclared identifier 'IPPROTO_IPV6'
if (setsockopt(sock, IPPROTO_IPV6, IPV6_V6ONLY, 
^
/root/.xmake/cache/packages/2306/f/flecs/v3.2.4/source/src/addons/http.c:1193:48: error: use of undeclared identifier 'IPV6_V6ONLY'
if (setsockopt(sock, IPPROTO_IPV6, IPV6_V6ONLY, 
^
/root/.xmake/cache/packages/2306/f/flecs/v3.2.4/source/src/addons/http.c:1261:24: error: variable has incomplete type 'struct sockaddr_in'
struct sockaddr_in addr;
^ …
```

Fix FreeBSD compilation

---

flecs.c
src/addons/rest.c

Previously when generating a reply for the entity and world REST API endpoints, the code ignored any errors, this meant it would send partial JSON data to the client with a 200 OK HTTP response.
This change instead checks if serialization was successful and if not will clear the body of the response and return a 500 Internal server error instead.

Don't return malformed JSON from REST API if serialization failed

---

flecs.c
flecs.h
include/flecs/addons/cpp/iter.hpp
src/iter.c
test/addons/src/util.c
test/api/src/util.c
test/cpp_api/src/Query.cpp
test/cpp_api/src/main.cpp

- Removes support for index 0 from:
- `ecs_field_w_size`
- `ecs_field_size`
- Ensure all the following functions assert that `index >= 1`
- `ecs_field_w_size`
- `ecs_field_is_readonly`
- `ecs_field_is_writeonly`
- `ecs_field_is_set`
- `ecs_field_is_self`
- `ecs_field_id`
- `ecs_field_column_index`
- `ecs_field_src`
- `ecs_field_size`
- Added `flecs::column<const flecs::entity_t> flecs::iter::entities()` to allow access to the iterators `entities` with the C++ API.
- Added `Query_iter_entities` to test the `flecs::iter::entities()` function.
I was attempting to write a filter like the following snippet and while doing so discovered that the `flecs::iter` was asserting when trying to access the field for the entities.
```cpp
std::vector<flecs::entity_t> allEntities;
ecs.filter_builder<>() …
```

Remove entities support from ecs_field functions

---

flecs.h
include/flecs/addons/cpp/mixins/pipeline/impl.hpp
include/flecs/addons/cpp/mixins/pipeline/mixin.inl

- Add `world::run_pipeline<T>(ecs_ftime_t)` overload
Was working with custom pipelines and noticed that this convenience overload was missing.
With this change instead of writing
```cpp
ecs.run_pipeline(ecs.id<CustomPipeline>().entity());
```
You can now just do
```cpp
ecs.run_pipeline<CustomPipeline>();
```

Add world::run_pipeline<T>(ecs_ftime_t) overload

---

flecs.h
include/flecs/addons/cpp/impl/world.hpp
include/flecs/addons/cpp/world.hpp
test/cpp_api/project.json
test/cpp_api/src/Singleton.cpp
test/cpp_api/src/main.cpp

- Added `world::target(int32_t index)` and `world::target(flecs::entity_t relationship, int32_t index)`
There was a [question asked on Discord](https://discord.com/channels/633826290415435777/1129888974475886672/1129888974475886672) about how to  get the target entity after doing something like the following:
```cpp
struct ActivePlayer {};
// ...
ecs.component<ActivePlayer>().add(flecs::Exclusive);
// ...
auto player = world.entity();
ecs.add<ActivePlayer>(player);
```
At the moment you can do this with (or some variation of):
```cpp
auto active_player = ecs.singleton<ActivePlayer>().target<ActivePlayer>();
```
With the change in this PR this now becomes more convenient to do, like so:
```cpp
auto active_player = ecs.target<ActivePlayer>();
```

Add world::target

---

include/flecs/os_api.h
src/addons/http.c

Remaining issues: 
- `flecs/src/addons/os_api_impl/windows_impl.inl:46:33: warning: incompatible pointer types passing 'int32_t *' (aka 'int *') to parameter of type 'volatile long *' [-Wincompatible-pointer-types]`
- `flecs/src/addons/os_api_impl/windows_impl.inl:53:33: warning: incompatible pointer types passing 'int32_t *' (aka 'int *') to parameter of type 'volatile long *' [-Wincompatible-pointer-types]`
- `flecs/src/addons/os_api_impl/windows_impl.inl:230:28: warning: implicit conversion from 'LONGLONG' (aka 'long long') to 'double' may lose precision [-Wimplicit-int-float-conversion]`
- `flecs/src/addons/http.c:341:30: warning: implicit conversion changes signedness: 'uint32_t' (aka 'unsigned int') to 'socklen_t' (aka 'int') [-Wsign-conversion]`
- `flecs/src/addons/http.c:352:29: …

Compiling flecs with clang-cl

---

flecs.c
flecs.h
include/flecs/addons/pipeline.h
src/addons/pipeline/pipeline.c
src/addons/pipeline/pipeline.h
src/addons/pipeline/worker.c
src/private_types.h
test/addons/project.json
test/addons/src/Pipeline.c
test/addons/src/main.c
test/cpp_api/project.json

- **Feature:** Added the ability for `ecs_run_pipeline` to execute multi-threaded systems on the worker threads.
- Added pipeline test cases: `run_pipeline_multithreaded` and `run_pipeline_multithreaded_tasks`.
- **Performance:**
- Improved the performance of workers by reducing the number of times the main thread needs to synchronize with the worker threads.
- Worker threads are no longer restarted when using `ecs_set_pipeline`
- **Bug:** Fixed a bug where if an empty pipeline was run it would cause `ecs_progress` to block forever ([Report on Discord](https://discord.com/channels/633826290415435777/1125769038337933352/1125774526786056223))
- I discovered during this work that the way `system_time_total` is measured with multi-threaded systems is not accurate as it only measures the work …

Multi-threaded custom pipelines

---

flecs.c
src/addons/pipeline/pipeline.c
src/addons/pipeline/pipeline.h
src/addons/pipeline/worker.c
src/datastructures/sparse.c

I was looking at changes from https://github.com/SanderMertens/flecs/pull/1003 again and realised there was some redundant code that could be cleaned up.
- Removed unneeded `if (main_thread || op->multi_threaded)` from `flecs_run_pipeline_ops`
- This isn't needed since `flecs_run_pipeline` only signals workers when `op->multi_threaded` is set.
- I turned this into an assert instead just to make sure it doesn't happen.
- Removed `bool main_thread` parameter from `flecs_run_pipeline_ops` since it is not needed.

Remove unneeded if and main_thread param from flecs_run_pipeline_ops

---

.github/workflows/ci.yml
examples/cpp/entities/iterate_components/src/main.cpp
flecs.h
include/flecs/private/api_defines.h

This PR makes the following changes:
- Add builds for gcc 12, gcc 13, clang 13, clang 14 and clang 15 to CI
- Fix warnings
- Cleanup CI jobs

Add additional compiler versions to CI

---

flecs.h
include/flecs/addons/cpp/mixins/pipeline/impl.hpp
include/flecs/addons/cpp/mixins/pipeline/mixin.inl
include/flecs/addons/cpp/world.hpp
test/cpp_api/src/Misc.cpp
test/cpp_api/src/World.cpp

**Changelog**
- Removes
- `ecs_ftime_t flecs::world::delta_time() const`
- `int64_t flecs::world::tick() const`
- `int64_t flecs::world::get_tick() const`
- `ecs_ftime_t flecs::world::time() const`
- `ecs_ftime_t flecs::world::get_time_scale() const`
- `ecs_ftime_t flecs::world::get_target_fps() const`
- Adds `const flecs::world_info_t* flecs::world::get_info() const` which all the above information can still be retrieved from.

Add world::get_info and remove unneeded functions

---

flecs.c
flecs.h
include/flecs/addons/cpp/mixins/meta/untyped_component.inl
include/flecs/addons/meta.h
src/addons/meta/meta.c
test/cpp_api/project.json
test/cpp_api/src/Meta.cpp
test/cpp_api/src/main.cpp
test/meta/include/meta.h
test/meta/src/StructTypes.c

- Added new pointer-to-member member function overload to `untyped_component`.
- Added support for packed structs in flecs meta.
- Removed unused `size` and `alignment` from `EcsMetaType`.
- Fixed bug where member count was ignored if an explicit offset was provided.
This new overload simplifies adding members with offsets and also helps ensure the offset is correct even if the structure changes or padding is inserted before/after fields, it also helps deal with offsets caused by inheritance with members or virtual functions.
<br/>
Using the example struct. I've included how this would usually be laid out in memory.
```cpp
struct SomeData {
char a;      // (Size: 1, Align: 1, Offset: 0)
int b;       // (Size: 4, Align: 4, Offset: 4)
char pad[2]; // (Size: 2, Align: 1, Offset: 8)
double c; …
```

Add pointer-to-member member function overload

---

include/flecs/addons/cpp/impl/world.hpp
include/flecs/addons/cpp/world.hpp

- added a method to get `flecs::scoped_world` by name

get flecs::scoped_world by name

---

CMakeLists.txt

Minor change to CMakelists.
versions before 3.5 are deprecated in latest CMake versions and causes a warning:
```
CMake Deprecation Warning at flecs/CMakeLists.txt:1 (cmake_minimum_required):Compatibility with CMake < 3.5 will be removed from a future version of
CMake.
Update the VERSION argument <min> value or use a ...<max> suffix to tell
CMake that the project does not need compatibility with older versions.
```

bump cmake_minimum_required version

---

flecs.h
include/flecs/addons/cpp/entity.hpp
include/flecs/addons/cpp/mixins/entity/builder.hpp
include/flecs/addons/cpp/world.hpp

~~I changed the comment of set_lookup_path dramatically to be aligned with the comment on the C function lookup_path, as it was a lot more descriptive. However, I used the @ parameters more heavily to split it up into sections.~~
after discussion with Sander, he instead suggested to use @see so there's no comment duplication across CPP/C API so @see has been added to set_lookup_path cpp function
I relocated the add enum function to be grouped with the other add functions. Same with Remove. 
The rest is quite minor.

fix/improve some comments, group add and remove functions

---

flecs.h
include/flecs/addons/cpp/impl/world.hpp
test/collections/src/Map.c
test/collections/src/Sparse.c
test/collections/src/Strbuf.c
test/cpp_api/project.json
test/cpp_api/src/Paths.cpp
test/cpp_api/src/main.cpp

it's worth considering if there should be a default parameter value for alias, which is set to nullptr.
In case you agree to remove it, I'll update the PR and 
`set ecs_check(entity != 0 || name != NULL, ECS_INVALID_PARAMETER, NULL); `
to
`ecs_check(entity != 0 && name != NULL, ECS_INVALID_PARAMETER, NULL);`
in
`flecs_set_identifier` function
In case we do, then the `if(!name)` check in `use` function is quite redundant and we could optionally remove it since flecs_set_identifier already deals will nullptr name where it just removes the previous alias and sets no new (as far as I understand)

set name if alias is nullptr for use

---

flecs.h
include/flecs/addons/cpp/entity.hpp

for the standard get_ref I'm passing it as a parameter, which should ensure registration too
for the other get_refs, it's already being registered in the function parameter passthrough too.

remove redundant get_ref component registration ensure

---

include/flecs/addons/log.h
src/addons/log.c
src/addons/pipeline/pipeline.c
src/addons/system/system.c
src/observer.c
src/poly.c
src/poly.h

As discussed on discord, moving the condition outside of `ecs_assert` improves debug performance. Now I also tested on ecs_benchmark and got ~1.4x speedups. 
For further work I need your opinion on 2 things:
1. The same could be done to `ecs_poly_assert`, but `ecs_poly` casts the return value from `ecs_poly_assert`. My suggestion is to do the check separately: [Example in my fork](https://github.com/jbarthelmes/flecs/commit/e00a9c15dbc549b34299d0162d12a353f9793206#diff-227b94484bf9df7691c3995c506646ee41f49e57356d50db1b55e00131767d15). Those 5 were the only callsites 2 weeks ago. Can you live with that?
2. Performance could be further improved (I measured ~1.3x) by removing the calls to `ecs_os_abort` and `assert`. This can be done by making the fail handler noreturn and moving the call to …

Improve assert performance

---

include/flecs/addons/cpp/delegate.hpp
include/flecs/addons/cpp/pair.hpp
include/flecs/addons/cpp/utils/utils.hpp
test/cpp_api/project.json
test/cpp_api/src/System.cpp
test/cpp_api/src/main.cpp

Modifies the templates for pairs in order to allow them to handle being used as an optional term in a system. It does this by adding `raw_type_t` to strip both pointers and references for most operations but adding `transcribe_pointer_t` to put them back when needed. This means that most of the code should end up handling this transparently without many changes but I've only tested systems right now.
Only tested with gcc currently as its all I had on me at the time.

Allow for optional pairs in C++ systems

---

flecs.c
src/addons/json/deserialize.c
src/addons/json/json.c
src/addons/json/json.h
src/addons/meta/cursor.c
test/meta/project.json
test/meta/src/Cursor.c
test/meta/src/DeserializeFromExpr.c
test/meta/src/DeserializeFromJson.c
test/meta/src/SerializeToExpr.c
test/meta/src/SerializeToJson.c
test/meta/src/main.c

This PR:
- Fixes a precision issue when parsing large (>32 bit) integers from JSON
- Fixes potential parsing issues on 32bit platforms (replaces `atol` with `atoll` where appropriate)
- Adds serialization/deserialization test cases for large ints

Fix issues with (de)serializing large integers

---

examples/c/observers/entity_event/src/main.c
examples/cpp/observers/entity_event/src/main.cpp
flecs.h
include/flecs/addons/cpp/component.hpp
include/flecs/addons/cpp/delegate.hpp
include/flecs/addons/cpp/mixins/event/decl.hpp
include/flecs/addons/cpp/mixins/event/entity_builder.inl
include/flecs/addons/cpp/mixins/event/entity_view.inl
include/flecs/addons/cpp/mixins/event/impl.hpp
include/flecs/addons/cpp/utils/function_traits.hpp
include/flecs/addons/cpp/utils/iterable.hpp
include/flecs/addons/cpp/utils/node_builder.hpp
include/flecs/private/api_defines.h
test/cpp_api/project.json
test/cpp_api/src/Event.cpp
test/cpp_api/src/main.cpp

This PR:
- adds the ability to emit events with a payload
- simplifies the callback signature of entity observers

Improve usability of entity observers

---

flecs.c
src/addons/pipeline/pipeline.c
src/entity.c
src/private_types.h
src/stage.c
src/stage.h
src/world.c
test/api/src/Commands.c

Fixes issue that can severely degrade performance of executing commands, particularly from observers in applications with lots of entities.
The issue was caused by a `flecs_sparse_clear` function that was used to clear the index used to track the start/end of command batches before executing commands in the queue. This function iterates all pages in the sparse set and memsets them to 0. For applications with large numbers of entities the number of pages could be a few dozen.
This added lots of relative overhead especially when small/empty command buffers which is typical for commands enqueued by observers.
In a local test with ~1 million entities, this fix reduced the time to create the entities from ~30 seconds to 0.2 seconds.

Don't use flecs_sparse_clear before executing command queue

---

meson.build
meson_options.txt

prevents the hello world example from being built by default when consumed as a subproject

make the hello world example optional when building via meson

---

examples/c/queries/sorting/src/main.c
examples/cpp/queries/sorting/src/main.cpp
flecs.h
include/flecs/addons/cpp/component.hpp

Since these are using single line comments, don't need to have `*/` at the end.

Remove redundant comment terminators.

---

flecs.c
src/addons/meta/api.c

The `min` and `max` fields are `double`, so we print them with `%f` rather than `%d`.

Print doubles as `%f`, not `%d`.

---

flecs.c
src/addons/rules/api.c
src/addons/rules/compile.c
src/addons/rules/engine.c
src/addons/rules/rules.h
test/addons/project.json
test/addons/src/RulesBasic.c
test/addons/src/RulesComponentInheritance.c
test/addons/src/RulesOperators.c
test/addons/src/RulesScopes.c
test/addons/src/main.c

This PR: 
- Reimplements control flow instructions (aka query operators) for the rule engine
- Adds filtering on disabled/prefab entities

Overhaul control flow instructions of rule engine

---

flecs.h
include/flecs/addons/cpp/world.hpp

From discord: https://discordapp.com/channels/633826290415435777/1187146437096648755
These functions are missing `func<First>(second)` overloads. This PR adds them.

Add missing overloads for delete_with and remove_all

---

examples/cpp/relationships/union/src/main.cpp

Fixes an example that is currently broken due to a change where .with<T> requests no data by default.
Another fix could have been to use .term<T> instead, but it's useful to see .with<T> and access modifiers in action.

Fix relationship example by specifying inout.

---

flecs.c
src/addons/meta/serialized.c
test/meta/project.json
test/meta/src/Serialized.c
test/meta/src/main.c

Fixes a crash if a meta member is added that doesn't have `EcsMetaType`.
Previously in `flecs_meta_serialize_struct` when `flecs_meta_serialize_type` was called it would log a message and `return -1` directly after which it would call `op = flecs_meta_ops_get(ops, cur);` which would access an index out of bounds of the ops array.

Handle missing metatype

---

flecs.c
src/addons/rules/engine.c
src/filter.c
src/query.c

Fills out the ``ecs_iter_t.system`` field with the entity id associated with the filter/query/rule if it has one.

Fill out ecs_iter_t.system field when iterating filters, queries, and rules

---

flecs.h
include/flecs/addons/cpp/mixins/system/builder_i.hpp
include/flecs/addons/cpp/mixins/timer/impl.hpp
include/flecs/addons/cpp/mixins/timer/mixin.inl
include/flecs/addons/cpp/mixins/timer/system_mixin.inl
test/cpp_api/project.json
test/cpp_api/src/System.cpp
test/cpp_api/src/main.cpp

- Added `flecs::world::timer<T>()`
- Added `flecs::system_builder_i::tick_source<T>()`
- Added `flecs::system::set_tick_source<T>()`
This allows associating timers and tick sources with a type, effectively a singleton timer.

Support associating a timer or tick source with a type

---

docs/Quickstart.md

Right now the live documentation website has a broken link in Flecs Quickstart for "System", this should fix it.

Fixed documentation link for System in "Flecs Quickstart" Addons section

---

flecs.h
include/flecs.h

Things were using adding themselves to the group `observers` but the group was created as `observer`. The other similar things all use plural names, so creating this as `observers` instead.

docs: Fix observers grouping.

---

flecs.h
include/flecs.h
include/flecs/addons/alerts.h
include/flecs/addons/app.h
include/flecs/addons/expr.h
include/flecs/addons/flecs_c.h
include/flecs/addons/http.h
include/flecs/addons/json.h
include/flecs/addons/log.h
include/flecs/addons/meta.h
include/flecs/addons/metrics.h
include/flecs/addons/module.h
include/flecs/addons/parser.h
include/flecs/addons/pipeline.h
include/flecs/addons/plecs.h
include/flecs/addons/rest.h
include/flecs/addons/rules.h
include/flecs/addons/snapshot.h
include/flecs/addons/stats.h
include/flecs/addons/system.h
include/flecs/addons/timer.h

This changes things to use `ecs_foo()` rather than `ecs_foo` so that doxygen's auto-linking will work.

docs: Link function names in doc comments.

---

flecs.c
flecs.h
include/flecs/private/vec.h
src/addons/snapshot.c
src/datastructures/vec.c

I was browsing the code and noticed this case could be optimized.
1. Use `ecs_vec_init` then `ecs_vec_set_count` instead of `ecs_vec_copy`.
Removes 1 copy.
2. Use `copy_ctor` instead of `ctor` then `copy`.
Best case removes unnecessary initialization.
Worse case no change.
`ti->hooks.ctor` is always set if `ti->hooks.copy` is set, so we also remove a redundant branch.
Another thing I noticed is that the duplicated table could previously have empty space at the end since the vectors get size to the nearest power of 2, because snapshots don't get modified there isn't any need for this empty space so we could save some memory by only allocating vectors for the exact number of rows that is in the table.
This does mean that after restoring a snapshot adding an entity will cause table …

Reduce copies when duplicating tables with non-POD components for snapshots

---

flecs.h
include/flecs/addons/cpp/mixins/app/mixin.inl
include/flecs/addons/cpp/mixins/filter/mixin.inl
include/flecs/addons/cpp/mixins/observer/mixin.inl
include/flecs/addons/cpp/mixins/pipeline/mixin.inl
include/flecs/addons/cpp/mixins/query/mixin.inl
include/flecs/addons/cpp/mixins/rule/iterable.inl
include/flecs/addons/cpp/mixins/rule/mixin.inl
include/flecs/addons/cpp/mixins/snapshot/mixin.inl
include/flecs/addons/cpp/mixins/system/builder_i.hpp
include/flecs/addons/cpp/mixins/system/mixin.inl
include/flecs/addons/cpp/mixins/term/decl.hpp
include/flecs/addons/cpp/mixins/term/mixin.inl
include/flecs/addons/cpp/mixins/timer/system_mixin.inl

Most of these are to correct unbalanced grouping. Two fixes are to correct a reference to a group name.

docs: Fix more doxygen warnings.

---

.github/workflows/ci.yml

`macos-latest` is currently `macos-12`. `macos-14` will become `macos-latest` in some months. `macos-14` runs exclusively on Apple Silicon hardware.

ci: Add some macOS-14 jobs on Apple Silicon.

---

docs/Quickstart.md
docs/RestApi.md

- Adds tabs for snippets in the `RestApi.md` and `Quikstart.md` docs.
See:
- https://zeroerrors.github.io/flecs/md_docs_2Quickstart.html
- https://zeroerrors.github.io/flecs/md_docs_2RestApi.html

Docs snippet tabs Part 2

---

flecs.h
include/flecs/addons/cpp/mixins/filter/impl.hpp
include/flecs/addons/cpp/mixins/snapshot/impl.hpp
include/flecs/addons/cpp/mixins/term/impl.hpp
include/flecs/addons/cpp/utils/builder.hpp
include/flecs/addons/cpp/utils/string.hpp
include/flecs/addons/cpp/utils/stringstream.hpp
include/flecs/addons/cpp/world.hpp
test/cpp_api/include/cpp_api.h
test/cpp_api/src/ComponentLifecycle.cpp

Defaulted move ctors and operator= will be `noexcept` when possible automatically.

c++: Mark all explicit move ctors and operator= as `noexcept`.

---

docs/Quickstart.md
docs/RestApi.md
docs/Systems.md

Added C# code snippets to the docs using the new tabs feature introduced in this PR https://github.com/SanderMertens/flecs/pull/1138. I only provided snippets for the quickstart, rest api, and system manual since those are currently the only pages using tabs right now.
A live version can be viewed with these links:
- [Quick Start](https://beancheeseburrito.github.io/flecs/md_docs_2Quickstart.html)
- [System Manual](https://beancheeseburrito.github.io/flecs/md_docs_2Quickstart.html)
- [Rest Api](https://beancheeseburrito.github.io/flecs/md_docs_2Quickstart.html)

Add C# code snippets to the docs

---

flecs.c
flecs.h
include/flecs/addons/cpp/mixins/json/world.inl
include/flecs/addons/json.h
src/addons/alerts.c
src/addons/json/deserialize.c
src/addons/json/json.c
src/addons/json/json.h
src/addons/json/serialize.c
src/addons/meta/cursor.c
src/addons/meta/meta.c
src/addons/metrics.c
src/addons/plecs.c
src/addons/rest.c
src/misc.c
src/private_api.h
test/api/src/main.c
test/meta/project.json
test/meta/src/DeserializeFromJson.c
test/meta/src/main.c

This PR implements the following features & bugfixes:
- Order of component registration no longer needs to match between serialization/deserialization
- Fix issues with deserializing entities/members with large names (>256 characters)
- Fix off-by-one issue with deserializing strings that are exactly 256 characters
- Ignore serialized values for components for which no/mismatching reflection data exists
- Introduce new strict mode that enables the old behavior
- Implement check that ensures a type with mismatching reflection data only throws one error (vs. one per value)
- Add `ecs_world_from_json_file` / `world::from_json_file` function that loads JSON data from file
- Significantly reduce creation of empty tables during deserialization

Improve robustness when deserializing JSON into  worlds with mismatching reflection data

---

flecs.c
flecs.h
include/flecs/addons/cpp/c_types.hpp
include/flecs/addons/cpp/impl/world.hpp
include/flecs/addons/cpp/mixins/alerts/impl.hpp
include/flecs/addons/cpp/mixins/meta/impl.hpp
include/flecs/addons/cpp/mixins/metrics/impl.hpp
include/flecs/addons/cpp/mixins/monitor/decl.hpp
include/flecs/addons/cpp/mixins/monitor/impl.hpp
src/bootstrap.c
test/custom_builds/cpp/no_auto_registration/src/main.cpp

This PR ensures that flecs components are registered when their module is imported. This prevents relying on automatic component registration, and makes builtin components play nice with the `FLECS_CPP_NO_AUTO_REGISTRATION` macro.

Register builtin components in C++ API

---

flecs.c
src/misc.c

This removes a warning when using `clang-tidy` as `rewind()` can't report errors while `fseek()` can. (Not that we're checking for errors here anyway...)

Use `fseek(file, 0, SEEK_SET)` instead of `rewind(file)`.

---

.github/workflows/ci.yml

The macOS 11 build runners are being deprecated and are intended to be removed by the middle of 2024:
https://github.com/actions/runner-images/issues/9255
Additionally, macOS-12 is to be deprecated in Q3 and removed in Q4, so prepare for that now by adding a macOS-13 build.

ci: Remove macOS-11 builds, add macOS-13.

---

flecs.h
include/flecs/addons/cpp/entity_view.hpp
include/flecs/addons/cpp/impl/world.hpp
include/flecs/addons/cpp/mixins/entity/builder.hpp
include/flecs/addons/cpp/mixins/meta/untyped_component.inl
include/flecs/addons/cpp/utils/enum.hpp
include/flecs/addons/cpp/utils/utils.hpp
test/cpp_api/project.json
test/cpp_api/src/Enum.cpp
test/cpp_api/src/Misc.cpp
test/cpp_api/src/main.cpp

This modifies the storage of enum reflection data from a sparse array lookup table to a contiguous-array with both lookup table/linked list scanning strategies.
Changes enum constants array constant (default) size of 128 to a compile-time determined size based on number of enum constants found during reflection.
Modified enum reflection search mechanisms by:
- Finds 0->128 in ascending order.
- Generates 0->128 by recursively dividing range, reducing the template depth from n to ln(n).
- Additionally finds bitmasks from `1 << (sizeof(underlying_type) * 8 - 1)` until it reaches the value used by the previous search (128).
It maintains a `contiguous_until` index, which is used to track the last default enum value. This is used as a heuristic to shortcut iteration, and direct lookup in the …

Changed enum constants to keep contiguous array and modifies index/search strategy

---

include/flecs/addons/cpp/mixins/entity/builder.hpp
include/flecs/addons/cpp/mixins/system/builder_i.hpp
test/cpp_api/project.json
test/cpp_api/src/System.cpp

With the addition of using enums as entity ids, there are a few places where the API takes an flecs::entity_t, but not an enum.  I've added a few of those cases.

Additional overloads for enum entities

---

flecs.c
src/bootstrap.c
src/entity.c
test/addons/project.json
test/addons/src/Modules.c
test/addons/src/main.c
test/api/src/main.c
test/cpp_api/project.json
test/cpp_api/src/Module.cpp
test/cpp_api/src/main.cpp

Add EcsModule to component parents if they exist. This is to avoid deletion of namespace entities during world fini, which can lead to component deletion before observers have a chance to fire.

Add EcsModule to component-parents

---

flecs.c
src/observable.c
test/api/project.json
test/api/src/ComponentLifecycle.c
test/api/src/main.c

fix memory read/write access in out of bounds memory on copying components when using ECS operations where count > 1, such as nested_prefabs
without this fix, the newly introduced test case would segfault. This bug happens due to the fact that in C you loop count times, but also offset the dest_ptr, and then within the copy impl of C++, it loops count again, this means you would go count-1 * size_obj out of memory bounds for src as well as dest ptr.
This fix is the correct fix as it limits src ptr to just 1, while the dest ptr still gets offset each iteration.
(this was previously discussed with sanders, the information above is just for tracking why & what)

fix memory read/write access in out of bounds memory on copying comps

---

flecs.c
src/storage/table.c
test/cpp_api/project.json
test/cpp_api/src/ComponentLifecycle.cpp
test/cpp_api/src/main.cpp

This changes the code in `flecs_table_merge_column` to not have `flecs_table_grow_column` default construct components in the new rows added to the column and instead handle it via `ctor_move_dtor` instead. This allows components that cannot be default constructed to be moved into existing tables.

Fix an assert when moving a component without a ctor to an existing table

---

flecs.c

When using the OS allocator, `flecs_balloc_block()` is unused and can be removed. Also, the `src` parameter to `flecs_brealloc()` is not used.

Fix warnings when `FLECS_USE_OS_ALLOC`.

---

flecs.h
include/flecs/addons/cpp/entity.hpp

entity's should not represent possibly pairs which are a possibility with id_t. 
Hence the change.

change entity constructor to take entity_t instead of id_t

---

docs/Relationships.md
flecs.c
flecs.h
include/flecs.h
include/flecs/addons/cpp/c_types.hpp
include/flecs/addons/cpp/impl/world.hpp
include/flecs/private/api_flags.h
src/addons/doc.c
src/bootstrap.c
src/entity.c
src/entity_filter.c
src/private_api.h
src/search.c
src/storage/id_index.c
src/storage/table.c
src/world.c
test/api/project.json
test/api/src/Pairs.c
test/api/src/main.c
test/cpp_api/src/World.cpp
test/cpp_api/src/main.cpp
test/custom_builds/cpp/no_auto_registration/src/main.cpp

This PR adds three new traits:
- A `Relationship` trait, which enforces that an entity can only be used as a relationship
- A `Target` trait, which enforces that an entity can only be used as a relationship target
- A `Trait` trait, which marks a property/trait as a trait

Pair constraints

---

flecs.c
src/storage/table.c
test/addons/src/main.c
test/api/project.json
test/api/src/ComponentLifecycle.c
test/api/src/main.c
test/collections/src/main.c
test/meta/src/main.c

If neither move nor move_ctor are set, this indicates that non-destructive move 
semantics are not supported for this type. In such cases, we set the move_dtor
as ctor_move_dtor, which indicates a destructive move operation. 
This adjustment ensures compatibility with different language bindings.

use destructive move semantics when move & move_ctor is not set. 

---

include/flecs/addons/cpp/entity.hpp
test/cpp_api/src/Refs.cpp

First time creating a pull request, I'm sorry in advance if I did something the wrong way !
This pull request adds a pair overload to `get_ref` to support pair types, so that a ref to the actual type is returned rather than a ref to the pair.
Here is a repro : 
```cpp
struct A {};
struct B {int value {0};};
using AB = flecs::pair<A, B>;
using SharedAB = flecs::pair<A, flecs::ref<B>>;
int main(int argc, char **argv)
{
flecs::world world;
auto a = world.entity("a");
auto b = world.entity("b");
a.add<AB>();
b.set<SharedAB>({a.get_ref<AB>()});// This doesn't work. 
// Returns flecs::ref<flecs::pair<A, flecs::ref<B>>>
b.set<SharedAB>({a.get_ref<A, B>()}); // A workaround
// Returns flecs::ref<B>
}
```
Changes were made to the normal `get_ref` to dissambiguate with the newly added overload.

Add pair overload to get_ref

---

src/world.c

Statically computes the compiler version string rather than determining it at runtime. resolves #1192

Prevent buffer overflow with large compiler version strings

---

include/flecs/addons/cpp/component.hpp
include/flecs/addons/cpp/utils/signature.hpp

This PR is based on one sleepless night and a similar [PR for entt](https://github.com/skypjack/entt/pull/1047).
The problem is that we get compilation errors when using the methods (when include flecs.h in global module fragment):
```cpp
world.import<ModuleName>();
world.system<ComponentName>();
// And perhaps others that call some template functions, the corrections of which are given in this PR
```
The reason to be that certain function declarations that are implicitly required by the implementation aren't exported into the module interface since they are marked 'static' and have internal linkage.
And when compiling we get the following error (clang-18 ubuntu 24.04 package version 1:18.1.3-1):
```console
/home/alexv/Desktop/flecs/include/flecs/private/../addons/cpp/mixins/term/../../uti …
```

CXX-20 MODULES - global module fragment support

---

flecs.c
flecs.h
include/flecs/private/api_flags.h
src/query.c
src/storage/table_cache.c
src/storage/table_cache.h
test/api/project.json
test/api/src/Query.c
test/api/src/main.c

This PR adds the ability to match empty tabes in cached queries. This is primarily intended as a performance optimization, as it prevents having to notify a query of table empty/non empty events, and is especially useful in applications that already cleanup empty tables frequently.

Add support for matching empty tables for cached queries

---

flecs.h
include/flecs/addons/cpp/mixins/event/builder.hpp
test/cpp/project.json
test/cpp/src/Event.cpp
test/cpp/src/main.cpp

Adds ability to create events with enum component ids via `event_builder_base::id(Enum::Value)` specialization, and adds companion test.
Replaces #1210 (master PR) for v4 branch

[v4] Added Enum specialization for event_builder_base::id(Enum::Value)

---

flecs.h
include/flecs/addons/cpp/delegate.hpp

When compiling against v4, I was getting the following error:
`include/flecs/flecs.h:25486:20: error: return-statement with a value, in function returning ‘void’ [-fpermissive]`
```c++
25486 |         return func(flecs::entity(iter->world, iter->entities[i]),
|                ~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
25487 |             (ColumnType< remove_reference_t<Components> >(comps, i)
|             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
25488 |                 .get_row())...);
```

[v4] Fixes return with a value in void function 

---

docs/cfg/Doxyfile
docs/cfg/custom.css
docs/cfg/github-dark.css
docs/cfg/header.html
docs/cfg/highlight.min.js
docs/cfg/languages/cpp.min.js
docs/cfg/languages/json.min.js
docs/cfg/languages/lua.min.js
docs/cfg/languages/rust.min.js
docs/cfg/languages/swift.min.js

adds syntax highlighting for cpp (c# will use this one), swift, lua, rust, json
in the form of:
```
<pre><code class="language-rust">
fn main() {
println!("Hello, world!");
}
</code></pre>
```
This is useful for bindings or the DSL language for docs

add swift/rust/cpp/lua/json syntax highlighting to docs

---

src/addons/rules/api.c
src/addons/system/system.c
src/filter.c
src/observer.c
src/query.c

**Note:** The changes were made against v3.11.2, *not* master. Hopefully they'll be useful anyway.
---
The error in question: (plus others, for each case of a casted dtor function pointer)
```
<...>/flecs/src/bootstrap.c:142:8: runtime error: call to function flecs_observer_fini through pointer to incorrect function type 'void (*)(void *)'
<...>/flecs/src/observer.c:1017: note: flecs_observer_fini defined here
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior <...>/flecs/src/bootstrap.c:142:8 
```

Fix issue where the use of a function pointer cast can trip -fsanitize=undefined on recent versions of clang

---

flecs.c

This should fix a _very obscure_ issue I was running into when cross-compiling from WSL using `x86_64-w64-mingw32-gcc-posix`, where WINVER was not defined and _WIN32_WINNT was 0x502 (Windows Server 2003) which was not a recent enough version to use `inet_pton` which caused some issues with #include's.
Solution based on this article from Microsoft which details how to manually set these values: https://learn.microsoft.com/en-us/cpp/porting/modifying-winver-and-win32-winnt?view=msvc-170

Ensure Windows version macro is minimum required to include inet_pton

---

flecs.h
include/flecs/addons/cpp/iter.hpp
test/cpp_api/project.json
test/cpp_api/src/Observer.cpp
test/cpp_api/src/main.cpp

As per [our discussion in Discord](https://discord.com/channels/633826290415435777/1032491261548044299/threads/1237529263733735524), here is a convenience method to access what term triggered an observer, along with a test.

Add term_index method to cpp iterator

---

docs/Quickstart.md

The latest release of flecs uses an array for events in the description of observer

Update Quickstart observer to use 'events' instead of 'event'

---

flecs.h
include/flecs/addons/cpp/mixins/entity/builder.hpp

This fixes cross-linking for existing `@see` stuff by supplying the `const` modifier.
An instance of trying to link to `override` instead of `auto_override` was adjusted.
It adds some missing parameter documentation.
A line wrapping mishap in `emplace_auto_override` was also corrected.

Improve entity builder docs.

---

docs/Systems.md

The code should refer to `Transform` as the other languages and docs do.

docs(systems): Rust: Fix referring to wrong component.

---

flecs.h
include/flecs/addons/cpp/delegate.hpp
test/cpp/src/Event.cpp
test/cpp/src/Query.cpp
test/cpp/src/main.cpp

Updates several places that call a user-provided callable to select overloads using SFINAE rather than determining function arity using the callable's type. This allows generic lambdas to be used in places where they previously weren't allowed.
Resolves #1233.

Add support for generic callables to delegates

---

flecs.h
include/flecs/addons/json.h

There is no implementation for this function anymore.

[v4] Remove ecs_ptr_from_json_legacy

---

docs/FlecsRemoteApi.md
flecs.c
flecs.h
include/flecs/addons/json.h
src/addons/json/deserialize.c
src/addons/json/json.c
src/addons/json/json.h
src/addons/json/serialize_entity.c
src/addons/json/serialize_iter_result.c
src/addons/json/serialize_iter_result_table.c
src/addons/meta/definitions.c
src/addons/rest.c
src/entity_name.c
test/addons/src/Rest.c
test/cpp/src/Enum.cpp
test/meta/project.json
test/meta/src/DeserializeFromJson.c
test/meta/src/SerializeEntityToJson.c
test/meta/src/SerializeIterToJson.c
test/meta/src/SerializeIterToRowJson.c
test/meta/src/main.c

- Make full path serialization the default
- This fixes an issue where `to_json`/`from_json` weren't symmetric
- Hide name/`ChildOf` components by default since they're serialized as `name`/`parent` fields
- Fix issue where anonymous variable entity could result in invalid JSON
- Other minor bugfixes

Json fixes

---

flecs.h
include/flecs/addons/cpp/world.hpp
test/cpp/project.json
test/cpp/src/World.cpp
test/cpp/src/main.cpp

When inadvertently copying a `flecs::world` object during shutdown, e.g., as part of a component `on_remove` hook, `ecs_fini()` is re-entered causing an abort.
Reproduction: 
```cpp
struct A {
int a;
};
flecs::world ecs;
// declare on remove hook for component A:
ecs.component<A>().on_remove([](flecs::entity e, A &) {  //
// This code runs on world destroy, since we did not remove this component manually
// before the world was destroyed.
// obtain the entity's world. This increments the hdr refcount when it already was zero
flecs::world ecs_copy = e.world();
// here ecs_copy object wrapping c world is destroyed, and `world::~world()` for this copied instance
// will be called, causing a repeated call to `ecs_fini()`
// therefore, world destroy will be called again wreaking havoc.
}); …
```

[v4] Fix crash when copying world cpp object during fini

---

flecs.c
flecs.h
include/flecs/private/api_flags.h
src/query/compiler/compiler.c
src/query/engine/cache_iter.c
src/query/engine/eval.c
src/query/engine/eval_iter.c
src/query/engine/trivial_iter.c
src/query/engine/trivial_iter.h
src/query/types.h
src/query/util.c
src/query/validator.c
test/query/src/Plan.c

This PR:
- Fixes an issue where the first term of an uncached query was evaluated twice
- Reduces branching in iterator code
- Add dedicated functions for uncached queries that are entirely trivial
- Remove dedicated function for uncached wildcard queries

Query iterator performance improvements

---

flecs.h
include/flecs/addons/cpp/flecs.hpp
include/flecs/addons/cpp/ref.hpp
test/cpp/project.json
test/cpp/src/Refs.cpp
test/cpp/src/main.cpp

flecs::ref<T> is a really useful object, but it's constructor is a bit weird.  It only takes a world_t* and an entity_t, both are encapsulated in the flecs::entity struct.  
So I added a constructor that simply takes a flecs::entity and extracts the world_t* and entity_t from that.  
There was a slight issue adding it because of how the flecs.hpp includes were laid out.  flecs::world has a get_ref<T>() which returns singletons, and expects ref to be declared before it.  I simply forward declared it in flecs.hpp like component is, and it seemed to like that.  
Also I'm kinda yoloing this PR cause I dont have bake setup on this new dev environment.  Hopefully the tests pass :)
Ok, tests passed, and I slipped in an operator bool() overload so 
```cpp
flecs::ref<Position> r(e);
if(r)
{
//... …
```

add a constructor for flecs::ref<T> that just takes the entity

---

examples/c/observers/yield_existing/src/main.c
examples/cpp/observers/yield_existing/src/main.cpp

This feature was removed in v4, so shouldn't be mentioned in the examples.

yield_existing: Examples refer to `EcsIterable`

---

.gitattributes

preserve line endings when building and testing on windows.

chore: create .gitattributes

---

flecs.c
flecs.h
include/flecs/addons/cpp/mixins/meta/untyped_component.inl
include/flecs/addons/meta.h
src/addons/meta/definitions.c
src/addons/meta/meta.c
test/cpp/project.json
test/cpp/src/Enum.cpp
test/cpp/src/Meta.cpp
test/cpp/src/main.cpp
test/meta/src/SerializeEntityToJson.c

This allows to register fields in arbitrary order for reflection. This is useful for example where in Rust fields are not guaranteed to be in the same order as represented.

add option to explicitly use provided offset, even when 0.

---

flecs.c
flecs.h
include/flecs/private/api_defines.h
src/query/engine/cache.c
src/query/types.h

This PR reduces memory consumption for cached queries, and improves cache locality during cached query iteration.

Reuse sources/id arrays for cached query results that have static values

---

flecs.c
src/observer.c
test/cpp/project.json
test/cpp/src/Observer.cpp
test/cpp/src/main.cpp

I noticed C++ observers with sparse components cause this assert to fire: 
`fatal: flecs.c: 10947: assert: !(idr->flags & EcsIdIsSparse) use ecs_field_at to access fields for sparse components (INVALID_OPERATION)`
A simple repro:
```cc
#include "flecs.h"
#include <iostream>
int main(int, char *[])
{
struct Position {
double x, y;
};
flecs::world ecs;
ecs.component<Position>().add(flecs::Sparse);
ecs.observer<Position>().event(flecs::OnSet).each([](flecs::entity e, Position& Pos)
{
std::cout << " - Position: {" << Pos.x << ", " << Pos.y << "}\n";
});
for (int i = 0; i < 4; ++i)
{
flecs::entity MeshEntity1 = ecs.entity();
MeshEntity1.set<Position>({1,2});
}
ecs.progress();
}
```
After some messing around I found that `each_delegate::invoke(ecs_iter_t *iter)` seems to expect `ref_fields` to …

Fix C++ API observers with sparse components by filling out iterator field flags in flecs_uni_observer_invoke

---

docs/Quickstart.md

Very small typo, but a bit confusing when I was new figuring `bake` out.

fix small typos in test running instructions

---

flecs.c
src/addons/meta/cursor.c
test/meta/project.json
test/meta/src/Cursor.c
test/meta/src/main.c

This PR allows cursors to get strings (`ecs_meta_get_string()`) from opaque types that behave like strings (`.as_type=ecs_string_t`).
This makes it symmetrical, since the opposite operation with `ecs_meta_set_string` which allows to set an opaque's underlying string, was already implemented.

Have ecs_meta_get_string() work with opaques with .as_type = string

---

flecs.c
src/query/compiler/compiler_term.c
src/query/engine/eval.c
src/query/engine/eval_iter.c
src/query/types.h
src/query/util.c
test/meta/src/SerializeQueryInfoToJson.c
test/query/src/Plan.c

This PR removes query instructions that optimize for terms that have static (non-wildcard) ids. The instructions were introduced as a performance optimization, but the `triv` instruction (which matches n trivial terms in a single call) makes these mostly redundant.

Remove redundant query instructions

---

test/meta/src/SerializeEntityToJson.c

While working on #1215 I noticed some tests of the meta add-on would not pass due to varying entity ids and for alerts, the order of alerts.
So I fixed two tests. For the first one, I gave entities fixed names so we would not be testing against entity ids which can vary.
For the second test, it is more complicated to make it perfect without a JSON library. The order of alerts in the alerts array is of undetermined order, causing the test to fail depending on arbitrary code changes elsewhere, Therefore I wrote an approximation searching for substrings to find the expected alerts in a deterministic way. This should be good enough I think.

Fix some flaky test in meta/ SerializeEntityToJson

---

test/cpp/src/Enum.cpp

CPP test `Enum_query_union_enum` was passing depending on compiler / platform due to query returning results in different order.
Fixed by adding all query results to a map and checking correct values deterministically.
Bug affects at least #1318, or whenever a new built-in component is added.

Fix flaky cpp/Enum test

---

distr/flecs.c
src/addons/meta/definitions.c
test/meta/project.json
test/meta/src/OpaqueTypes.c
test/meta/src/main.c

Note: Includes #1313, so that the tests would pass. It might make sense to review and merge that one first.
This PR implements an opaque type to represent read-only const strings stored in .rodata, so that the automatic destructor I am working on to fix #1215 ignores them, since no destructor is specified for this opaque type.
The PR also maps `build_info_t`'s reflection definition to use these const strings.
In conjunction with #1316, const strings are then more or less transparent from the reflection/cursor point of view. A cursor can read a const string, but won't be able to write to it, since it does not implement `assign_string` overload.

meta: const string implementation

---

distr/flecs.h
include/flecs/addons/cpp/world.hpp
test/cpp/project.json
test/cpp/src/World.cpp
test/cpp/src/main.cpp

Fixed bug when overwriting a flecs::World instance with another, either via copy-assign or move-assign. The existing world is not freed, causing a memory leak:
```cpp
flecs::world world1;
flecs::world world2;
world1 = world2;  // leaks, since underlying world_t* in world1 
// is not fini'ed before world2's ptr takes over.
// same happens if move-assign is used.
```
The PR fixes this issue and adds a test to watch over that.

fix copy/move-assign operators of World class not freeing existing world

---

distr/flecs.h
include/flecs/addons/cpp/component.hpp

Summary: This diff upstreams a fix that ensures that the C++ type/symbol names are computed at most once, and fixes an issue where the name buffers could be written to simultaneously by different threads.
Differential Revision: D62050989

Compute flecs C++ type/symbol name at most once

---

distr/flecs.h
include/flecs/addons/cpp/delegate.hpp
test/cpp/project.json
test/cpp/src/Query.cpp
test/cpp/src/main.cpp

- set is_ref in populate_self so that it's properly set for any type of query
- always set row to 0 for components with is_ref to avoid indexing garbage
Fixes #1324

Properly set and read is_ref in delegate.hpp to fix non-$this variable source components in query iteration

---

distr/flecs.c
src/entity.c
src/observable.c
src/private_api.h
test/core/project.json
test/core/src/Prefab.c

Summary: This upstreams a change that allows for deterministic generation of prefab instance child ids across networked applications.
Differential Revision: D62050990

Implement deterministic ids for prefab children

---

distr/flecs.h
include/flecs/private/api_defines.h

Summary: This upstreams a change that ensures that `__alignof__` is used when compiling with clang.
Differential Revision: D62051794

Use __alignof__ on clang

---

distr/flecs.c
src/world.c
test/core/project.json
test/core/src/World.c

Summary:
This diff upstreams two changes:
- Providing 0 for the `offset` parameter of `ecs_set_entity_range` will default to the max issued entity id
- Setting the `limit` parameter of `ecs_set_entity_range` to a value that is lower than a previously provided value is now allowed
Differential Revision: D62052785

Improve usability of ecs_set_entity_range function

---

distr/flecs.h
include/flecs/addons/cpp/ref.hpp
test/cpp/project.json
test/cpp/src/Refs.cpp
test/cpp/src/main.cpp

Summary: This diff upstreams a change that adds a `has` method to `flecs::ref`.
Differential Revision: D62446531

Add flecs::ref::has

---

distr/flecs.c
src/storage/table.c
test/core/project.json
test/core/src/Table.c
test/core/src/main.c

Summary: This diff upstreams a change that fixes an issue with testing a table for wildcard ids.
Differential Revision: D62449697

Fix issue with testing tables for wildcard pair ids

---

distr/flecs.c
src/entity.c
test/core/project.json
test/core/src/Clone.c
test/core/src/main.c

When working on #1330 I noticed that when copying an entity with `ecs_clone(...,true)`, a component's ctor was being called twice, the second time over already initialized memory. This causes a memory leak of components that allocate dynamic memory in the constructor.
Even if the component is trivial, the registered constructor was being called twice during a clone anyway. This PR fixes that and adds a test to make sure there are no leaks.
The bug does not affect copies created while instantiating a prefab.

fix leak in ecs_clone

---

test/meta/src/RuntimeTypes.c

When examining the diff again I saw a copy-paste error where I had overlooked replacing "array" with "vector". This fixes that. My apologies.

fixed copy-paste error in rtt tests

---

distr/flecs.h
include/flecs/addons/cpp/impl/iter.hpp
include/flecs/addons/cpp/iter.hpp
test/cpp/project.json
test/cpp/src/Observer.cpp
test/cpp/src/main.cpp

Summary: This diff upstreams a change that adds an `flecs::iter::other_table()` method.
Differential Revision: D62449718

Add flecs::iter::other_table()

---

distr/flecs.c
distr/flecs.h
include/flecs.h
include/flecs/addons/cpp/mixins/id/decl.hpp
src/addons/script/query_parser.c
src/entity.c
src/id.c
test/core/project.json
test/core/src/Id.c
test/core/src/main.c
test/cpp/project.json
test/cpp/src/Paths.cpp
test/cpp/src/main.cpp

Summary: This diff adds an `ecs_id_from_str` function that parses a (component) id expression into an id, and adds a `flecs::id::id(flecs::world_t*, const char*)` constructor.
Differential Revision: D63060151

Expose C/C++ functions to parse component id expressions

---

distr/flecs.c
src/addons/stats/monitor.c
test/addons/project.json
test/addons/src/Stats.c
test/addons/src/main.c

Summary: This diff fixes an assert that happens because the stats module does not correctly handle empty tables, which can be returned by queries if the application sets the global `EcsQueryMatchEmptyTables` flag.
Differential Revision: D63355531

Fix issue in flecs::stats module when global MatchEmptyTables flag is set

---

distr/flecs.c
src/datastructures/block_allocator.c

fixes error: flecs.c(28687): Error C2491 : 'flecs_bfree_w_dbg_info': definition of dllimport function not allowed

remove FLECS_API in block_allocator.c -> fixes dll import issue

---

distr/flecs.h
include/flecs/private/addons.h

I was having some runtime crash with FLECS_REST and FLECS_TIMER (the last one which the alerts module uses) while compiling flecs with zig, but wasn't unable to disable FLECS_ALERTS, so I'm assuming that's missing unintentionally and I'm adding it here \o

Add FLECS_NO_ALERTS support

---

distr/flecs.c
src/query/engine/eval.c
test/query/project.json
test/query/src/Basic.c
test/query/src/main.c

Summary: This diff fixes an issue with queries that are created with the `EcsQueryMatchEmptyTables` flag, and iterate individual entities vs. entire tables.
Differential Revision: D63857210

Fix issue with queries that match empty tables and iterate individual entities

---

distr/flecs.c
distr/flecs.h
include/flecs.h
src/storage/table.c
test/core/project.json
test/core/src/Table.c
test/core/src/main.c

Added ecs_table_clear_entities to allow users to clear a table's entities while optionally retaining its memory allocations. This can help reduce allocation churn when overwriting table entities using ecs_bulk_init. 
Discord Conversation: https://discord.com/channels/633826290415435777/1090412095893422101/1288146063982858242

Added ecs_table_clear_entities

---

distr/flecs.h
include/flecs/addons/cpp/utils/enum.hpp

Summary: Fix conflicting identifier between flecs and magic_enum that causes compilation to fail.
Differential Revision: D64483027

Fix conflicting identifier between flecs and magic_enum

---

distr/flecs.c
src/addons/flecs_cpp.c

Summary: Remove redundant call to strcpy in C++ component registration code.
Differential Revision: D64566958

Remove redundant call to strcpy

---

distr/flecs.c
src/addons/meta/meta.c
test/meta/project.json
test/meta/src/EnumTypes.c
test/meta/src/main.c

This PR makes sure that when an enum changes, observers on `EcsEnum` (`flecs::Enum`) are notified.
This makes the api coherent with structs, that is, when a member is added to a struct, observers watching `EcsStruct` (`flecs::Struct`) are notified.
Normally, structs/enums/etc are only modified during startup logic as they are constructed. These notifications help serialization libraries synchronize what they know about the type.

[meta] Notify on enum modifications

---

MODULE.bazel
examples/build/bazel/README.md

The version attribute is not required in bazel module definitions. Currently, the only way to depend on flecs with bzlmod is through `git_override`, which overrides the version with a specific commit anyways. if flecs becomes distributed on Bazel central, this decision will need to be reevaluated, but for now, it's easier to leave it off instead of having to maintain keeping the module version up to date with the current release.
Also updated the docs with guidance on how to configure renovate to autoupdate flecs dependency.

Remove unnecessary version attribute from flecs bazel module definition

---

distr/flecs.c
src/world.c
test/core/project.json
test/core/src/World.c
test/core/src/main.c

Fixes #1391 
Delete command queue grew accumulating commands until the containing vector overflew `ecs_size_t` causing the issue mentioned in #1391.
This fix flushes commands in small batches during world end, avoiding excessive command queue growth.

Fix #1391 - Avoid command queue excessive growth on world fini

---

test/core/src/Table.c
test/cpp/src/Paths.cpp

This PR just removes some unused variables in a few tests that were giving out warnings during compilation.

[chore] Fix some annoying warnings in tests

---

distr/flecs.h
include/flecs/addons/cpp/component.hpp
include/flecs/addons/cpp/delegate.hpp
include/flecs/addons/cpp/mixins/event/impl.hpp
include/flecs/addons/cpp/utils/node_builder.hpp
include/flecs/addons/cpp/utils/utils.hpp

UBSan error was:
> call to function void flecs::_::free_obj<flecs::_::each_delegate<>> through pointer to incorrect function type 'void (*)(void *)'
It's caused by reinterpret_casting the free_obj template to ecs_ctx_free_t and then calling it through that function type. Changing the free_obj signature fixes it. However, I don't know if you're planning on checking UBSan, so this might not be something you care about. IMHO it improves readability to get rid of the reinterpret_casts, even though you lose type safety when calling free_obj  directly.

Fixed UBSan runtime error: calling function through pointer to incorrect type

---

distr/flecs.c
src/query/engine/cache.c
test/query/project.json
test/query/src/OrderBy.c
test/query/src/main.c

Summary: This issue fixes an assert that occurs when a query that is created with `EcsQueryMatchEmptyTables` (which is the default for HSR) and has an `order_by` callback, only matches empty tables.
Differential Revision: D66028916

Fix crash when sorted query with MatchEmptyTables flag only matches empty tables

---

distr/flecs.c
src/world.c
test/cpp/project.json
test/cpp/src/ComponentLifecycle.cpp
test/cpp/src/main.cpp

This fails on master now, no test catches it:
Hopefully we can fix it by the end of today together with other changes.
```cpp
struct Position {
int x;
int y;
// the following copy ctor will configure a copy_ctor hook:
Position(const Position &other) {
x = other.x;
y = other.y;
}
};
flecs::world ecs;
auto pos = ecs.component<Position>();
// later on, the user adds a `on_add` hook:
pos.on_add([](flecs::entity e, Position &) {}); // boom
```
This is because `ecs_set_hooks_id` may be called repeatedly to set one hook at a time. On the first call, the `ECS_TYPE_HOOKS` flags get calculated, and stored.
Code all over the place expects to be able to retrieve the hooks, make some changes (perhaps add a new hook) and then resubmit the modified hooks structure, inadvertently resubmitting already …

patch ecs_set_hooks_id being too strict with read-only flags

---

distr/flecs.h
include/flecs/addons/cpp/mixins/term/builder_i.hpp

Summary: Fix static_cast in flecs C++ API to use correct type.
Differential Revision: D66967950

Fix incorrect type in static_cast

---

distr/flecs.c
src/addons/http.c

When using the flecs_explorer_request hook from wasm with FLECS_NO_OS_API_IMPL set, the lack of threading support prevents the http server from being created. We don't need lock support if we don't plan to actually launch the resulting server, so move the check that we have that support to starting/stopping the server.

Move threading check in HTTP server to start/stop methods.

---

distr/flecs.h
include/flecs/addons/cpp/type.hpp
test/cpp/project.json
test/cpp/src/Entity.cpp
test/cpp/src/main.cpp

Summary:
This diff fixes a crash when iterating the type of an entity without components, like here:
```
flecs::entity e = world.entity();
for (auto id : e.type()) { // crash
}
```
Differential Revision: D67102905

Fix crash when iterating empty type

---

distr/flecs.c
src/observer.c
test/core/project.json
test/core/src/Observer.c
test/core/src/main.c

Summary:
This diff fixes a Flecs issue where mulit-component observers could get triggered multiple times for the same event. Two separate problems contributed to this issue:
1. Observers copied the wrong event id used to dedup events. Instead of using the event id passed by `flecs_emit`, observers used the global event id counter. In most cases these are the same, except when nested `flecs_emit` calls happen (which is rare).
2. The event id was copied at the wrong time. When a multi-component observer gets triggered, it still needs to verify if the event matches its query. Observers copied the event id before checking if the query matched, which could cause events to get skipped or delivered multiple times.
Differential Revision: D67219403

Fix issue where observers could be triggered multiple times for the same event

---

distr/flecs.c
src/misc.c

Calls to ```fclose()``` were missing in some cases when ```goto error``` was used.
Therefore, I added ```fclose()```.
The check ```if (file)``` is needed, because ```goto error``` is also used when file was not successfully opened.

Fix possible handle leak

---

distr/flecs.h
include/flecs/addons/cpp/delegate.hpp

This is used in the C++ API for iterating sparse component data and appears to cast to int8 instead of the intended int32.
Repro with making 2000 sparse components and iterating them in a system:
```cc
flecs::world ecs;
class Vec4Sparse {
public:
float F32[4];
};
ecs.component<Vec4Sparse>().add(flecs::Sparse);
for (int i = 0; i < 2000; ++i) {
auto e = ecs.entity().set<Vec4Sparse>({});
std::cout << " Made entity id: " << e.id() << "\n";
}
ecs.system<Vec4Sparse>().each([](flecs::entity e, Vec4Sparse& p) {
// crash happens in .each field templates
std::cout << e.id() << "Sparse data: {" << p.F32[0] << ", " << p.F32[1] << "}\n";
});
ecs.progress();
```

Fix each_ref_field not casting to int32_t for ecs_field_at_w_size's ow parameter

---

distr/flecs.h
include/flecs/addons/cpp/utils/enum.hpp

This PR fixes compilation warnings, at least in GCC, due to sign mismatch calculating `high_bit` in `enum.hpp` 
After #696 was merged, a warning appeared when compiling `enum.hpp`:
```
/flecs/private/../addons/cpp/utils/enum.hpp:264:49: warning: overflow in conversion from ‘int’ to ‘flecs::_::enum_reflection<Ei8, flecs::_::enum_data_impl<Ei8>::reflection_count>::U’ {aka ‘signed char’} changes value from ‘128’ to ‘-128’ [-Woverflow]
264 |     static const U high_bit = static_cast<U>(1) << (sizeof(U) * 8 - 1);
```
Inspite of the warning, the code works. The PR fixes this issue by calculating the high bit with an unsigned version, then casting back to the underlying enum type. This tells the compiler we really mean what we are doing.

Fix warnings in enum.hpp high bit calculation

---

meson.build

The App addon was missing from the meson build.

Add missing addons/app.c to meson.build

---

distr/flecs.c
src/observer.c
test/core/project.json
test/core/src/Observer.c
test/core/src/main.c

`flecs_default_next_callback` uses the `interrupted_by` field to decide if next should return true or false for systems using the run callback. `flecs_multi_observer_builtin_run` resets this before calling the callback but it was missing from `flecs_observer_invoke` meaning having two matching observers could cause the second one not to iterate when called.

Fix having two observers using run actions not working correctly

---

distr/flecs.h
include/flecs/addons/cpp/mixins/query/impl.hpp
test/cpp/project.json
test/cpp/src/Query.cpp
test/cpp/src/main.cpp

Copy ctor/assign for C++ queries would abort in `flecs_poly_claim` if called with a default initialized query. This fixes that and `flecs_poly_release` not being called for the query being copied over during assignment.

Fix query copy operations with default init queries

---

distr/flecs.c
src/addons/meta/api.c

This PR fixes an issue I found with `ecs_struct_init`. When attempting to initialize a struct with a member named `_` the member would silently not be created at all. The issue was that the method used to create the members, `ecs_entity`, would return the *any* entity instead of creating a new one. Swapping that method for `ecs_new_from_path` fixes the issue.

Fix members named `_` not being created in structs

---

distr/flecs.h
include/flecs/addons/cpp/mixins/term/builder_i.hpp
test/cpp/project.json
test/cpp/src/Enum.cpp
test/cpp/src/Observer.cpp
test/cpp/src/QueryBuilder.cpp
test/cpp/src/main.cpp

When calling ``term_builder_i::singleton()``, there's a typo where the term's source id isn't being set correctly for pairs (always 0) because it is creating and passing a new world  to ``ecs_get_alive`` instead of using the world that is returned by ``world_v()``. 
https://github.com/SanderMertens/flecs/blob/98d13a6907996bfc4c9faacddfc8b102a0b9af64/include/flecs/addons/cpp/mixins/term/builder_i.hpp#L404
Bake generated some missing enum tests so I included those as well.

Use correct world in term_builder_i::singleton(), Add missing enum tests

---

distr/flecs.c
distr/flecs.h
include/flecs.h
include/flecs/datastructures/map.h
src/addons/json/serialize_iter_result.c
src/addons/metrics.c
src/bootstrap.c
src/datastructures/block_allocator.c
src/datastructures/map.c
src/entity.c
src/observable.c
src/private_types.h
src/query/engine/eval.c
src/storage/id_index.c
src/storage/id_index.h
src/storage/table.c
src/storage/table.h
src/world.c

This PR has the following changes:
- Bypass block allocator for large chunk sizes
- Reduce footprint of `ecs_map_t`
- Move pair-only fields of `ecs_id_record_t` to separate struct that's only allocated for pairs
- Remove unused field from `ecs_table__t` and reorder fields to reduce padding

Reduce memory consumption

---

distr/flecs.h
include/flecs/addons/cpp/mixins/meta/opaque.hpp
include/flecs/addons/meta.h
test/cpp/project.json
test/cpp/src/Meta.cpp
test/cpp/src/main.cpp

This PR introduces two new opaque handlers that allow opaque implementers to provide random access to struct members or vector/array elements.
By defining `serialize_element` or `serialize_member`, the developer implementing the opaque can provide an interface to access an element or member directly.
For example, providing access to an `std::vector` item:
```cpp
// Reusable reflection support for std::vector
template<typename Elem, typename Vector = std::vector<Elem>>
flecs::opaque<Vector, Elem> std_vector_opaque(flecs::world &world) {
return flecs::opaque<Vector, Elem>()
.as_type(world.vector<Elem>())
.count([](const Vector *data) { return data->size(); })
.resize([](Vector *data, size_t size) { data->resize(size); })
.ensure_element([](Vector *data, size_t elem) {
if (data->size() <= …
```

[meta] Opaque random-access serializer for vectors/arrays and structs

---

distr/flecs.c
distr/flecs.h
include/flecs/private/api_types.h
src/entity.c
src/storage/table.c
src/storage/table.h
src/world.c
src/world.h

Summary: Upstream `ref_t` performance improvement from D72071960
Differential Revision: D72349829

Ref_t performance improvement

---

distr/flecs.c
distr/flecs.h
include/flecs/addons/meta.h
src/addons/flecs_cpp.c
src/addons/meta/api.c
src/addons/meta/c_utils.c
src/addons/meta/meta.c
test/meta/src/BitmaskTypes.c
test/meta/src/EnumTypes.c

Implemented with vector<ecs_enum_constants_t> and extended existing test to test the ordering.

Implemented ordered enum/bitmask constants #1594

---

README.md
docs/Quickstart.md

Adding the Clojure examples for the quickstart guide o/
Let me know if a new lang would be acceptable into the docs, Sander.
If it's undesired (because it's a niche lang or because you don't want to clutter the UI), I would totally understand, I'd just propose adding some kind of unique identifier for each example (see below) so anyone could replace/add code before the build for their own fork of the docs.
Something like
```html
.
.
.
.
.
.
.
.
.
```
Great docs btw!

[docs] Add Clojure lang to quickstart guide

---

distr/flecs.c
distr/flecs.h
include/flecs.h
src/id.c
src/query/cache/cache.c
src/query/cache/cache.h
src/query/cache/change_detection.c
src/query/cache/iter.c
src/query/cache/match.c
src/query/validator.c
test/query/project.json
test/query/src/Parser.c
test/query/src/Plan.c
test/query/src/TrivialIter.c
test/query/src/Validator.c
test/query/src/Variables.c
test/query/src/main.c

This PR:
- allows for creation of trivial caches with Not and Optional operators
- fixes an issue where `!(R, *)` terms were not cached

Allow more operators for trivial query caches

---

CMakeLists.txt

Previous versions to 3.10 is deprecated and cmake gives a warning
```
CMake Deprecation Warning at Coffee/vendor/flecs/CMakeLists.txt:1 (cmake_minimum_required):
Compatibility with CMake < 3.10 will be removed from a future version of
CMake.
Update the VERSION argument <min> value.  Or, use the <min>...<max> syntax
to tell CMake that the project requires at least <min> but has been updated
to work with policies introduced by <max> or earlier.
```

fix: bump cmake_minimum_required version

---

distr/flecs.c
distr/flecs.h
examples/c/script/functions/src/main.c
examples/c/script/script_run/src/main.c
examples/c/script/script_w_vars/src/main.c
include/flecs/addons/cpp/mixins/script/mixin.inl
include/flecs/addons/log.h
include/flecs/addons/script.h
src/addons/log.c
src/addons/meta/definitions.c
src/addons/rest.c
src/addons/script/parser.c
src/addons/script/script.c
src/addons/script/visit.c
src/addons/script/visit_eval.c
src/addons/script/visit_free.c
src/addons/script/visit_to_str.c
src/addons/stats/world_summary.c
test/addons/src/Rest.c
test/custom_builds/c/plecs/src/main.c
test/script/project.json
test/script/src/Error.c
test/script/src/Eval.c
test/script/src/ExprAst.c
test/script/src/Fuzzing.c
test/script/src/Template.c
test/script/src/main.c

- Allow scripts to be saved from the explorer
- Always store build info (version, build configuration) on world so it is available for the explorer
- Store script code even on errors so code is never lost after reloading explorer
- Store script errors so they can be shown on explorer reload

Improvements for script & explorer

---

docs/EntitiesComponents.md

In C++, the function for checking if a component is enabled is called `enabled` and not `is_enabled`.

Update docs/EntitiesComponents.md to change `is_enabled` to `enabled`

---

distr/flecs.h
include/flecs/addons/cpp/utils/utils.hpp

- Adds a `conditional` template that is faster to instantiate than std::conditional. I got this from here: https://github.com/facebook/fatal/blob/main/fatal/type/conditional.h and adapted it to my code and have been using it for awhile now here: https://github.com/dementive/lt/blob/main/src/lt/types/conditional.hpp.

Small compile time improvements
